import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { testingStatusLabel } from "@/lib/testing-requests";

export const dynamic = "force-dynamic";

export default async function AdminTestingPage() {
  const sb = createSupabaseServerClient();
  const { data: requests } = await sb.from("testing_requests").select("id,exam_code,testing_mode,status,payment_status,tester_first_name,tester_last_name,tester_email,accommodations_requested,submitted_at").order("submitted_at", { ascending: false });
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Exam Pre-Registration</h1><p className="mt-1 text-muted">Paid candidate requests awaiting ABCAC processing through SMT.</p></div></div><div className="mt-6 overflow-hidden rounded-2xl border border-line bg-surface"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-line bg-bg text-left text-xs uppercase tracking-wide text-muted"><th className="px-5 py-3">Tester</th><th className="px-5 py-3">Exam</th><th className="px-5 py-3">Mode</th><th className="px-5 py-3">Payment</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Submitted</th><th className="px-5 py-3"></th></tr></thead><tbody>{(requests ?? []).length === 0 ? <tr><td colSpan={7} className="px-5 py-10 text-center text-muted">No testing requests yet.</td></tr> : (requests ?? []).map((request: any) => <tr key={request.id} className="border-b border-line last:border-0"><td className="px-5 py-4"><p className="font-semibold">{request.tester_first_name} {request.tester_last_name}</p><p className="text-xs text-muted">{request.tester_email}</p>{request.accommodations_requested && <span className="mt-1 inline-block rounded-full bg-amber-100 px-2 py-0.5 text-[11px] font-semibold text-amber-800">Accommodations</span>}</td><td className="px-5 py-4 font-semibold">{request.exam_code}</td><td className="px-5 py-4 text-muted">{request.testing_mode === "remote" ? "Remote" : "In person"}</td><td className="px-5 py-4 capitalize text-muted">{request.payment_status}</td><td className="px-5 py-4 text-muted">{testingStatusLabel(request.status)}</td><td className="px-5 py-4 text-muted">{new Date(request.submitted_at).toLocaleDateString()}</td><td className="px-5 py-4"><Link href={`/admin/testing/${request.id}`} className="font-semibold text-brand">Review →</Link></td></tr>)}</tbody></table></div></div></>;
}
