"use client";

import { Button } from "@/components/ui/button";
import { siteConfig } from "@/lib/site-config";

export interface ReceiptData {
  /** Invoice number or payment reference shown on the receipt. */
  invoiceNumber?: string | null;
  /** Description / product name (member- or admin-provided — will be escaped). */
  description?: string | null;
  amountCents?: number | null;
  /** ISO date the item was paid. */
  paidAt?: string | null;
  /** Internal id printed for reference. */
  id?: string | null;
  /** Whom the receipt is billed to (member name and/or email — escaped). */
  billedTo?: string | null;
}

/** Escapes a value for safe interpolation into the printable HTML document. */
function esc(value: string | null | undefined): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function fmtDate(d: string | null | undefined): string {
  if (!d) return "—";
  const date = new Date(d);
  if (Number.isNaN(date.getTime())) return "—";
  return date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

function money(c: number | null | undefined): string {
  return "$" + ((c ?? 0) / 100).toFixed(2);
}

function openPrint(html: string) {
  const w = window.open("", "_blank");
  if (!w) return alert("Please allow pop-ups to download your receipt.");
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
}

function buildReceiptHtml(data: ReceiptData): string {
  const c = siteConfig.contact;
  const number = esc(data.invoiceNumber || data.id || "—");
  const description = esc(data.description || "Payment");
  const amount = esc(money(data.amountCents));
  const paid = esc(fmtDate(data.paidAt));
  const id = esc(data.id || "—");
  const billedTo = esc(data.billedTo || "");

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>ABCAC Receipt ${number}</title><style>
  @page{size:letter;margin:0}
  body{margin:0;font-family:Georgia,'Times New Roman',serif;color:#1c2430;background:#fff}
  .sheet{max-width:680px;margin:0 auto;padding:56px 56px 40px;box-sizing:border-box}
  .head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #1f3a5f;padding-bottom:18px}
  .org{max-width:360px}
  .org h1{color:#1f3a5f;font-size:20px;line-height:1.25;margin:0 0 8px}
  .org p{margin:1px 0;font-size:12px;color:#4a5568}
  .badge{text-align:right}
  .badge .label{text-transform:uppercase;letter-spacing:3px;font-size:12px;color:#806014}
  .badge .paid{display:inline-block;margin-top:8px;padding:4px 12px;border:2px solid #1f7a44;color:#1f7a44;border-radius:6px;font-size:13px;font-weight:bold;letter-spacing:1px;text-transform:uppercase}
  .meta{display:flex;gap:48px;margin:28px 0 8px;font-size:13px}
  .meta .k{text-transform:uppercase;letter-spacing:1px;font-size:11px;color:#806014;margin-bottom:3px}
  .meta b{font-size:14px}
  table{width:100%;border-collapse:collapse;margin:24px 0 0;font-size:14px}
  thead th{text-align:left;text-transform:uppercase;letter-spacing:1px;font-size:11px;color:#806014;border-bottom:2px solid #c8a04a;padding:0 0 8px}
  thead th.r,tbody td.r{text-align:right}
  tbody td{padding:14px 0;border-bottom:1px solid #e2e8f0}
  tfoot td{padding:16px 0 0;font-size:16px;font-weight:bold}
  tfoot td.r{text-align:right;color:#1f3a5f}
  .foot{margin-top:40px;border-top:1px solid #e2e8f0;padding-top:16px;font-size:12px;color:#4a5568;text-align:center;line-height:1.6}
  </style></head><body>
  <div class="sheet">
    <div class="head">
      <div class="org">
        <h1>${esc(siteConfig.name)}</h1>
        <p>${esc(c.org)}</p>
        <p>${esc(c.addressLine)}</p>
        <p>${esc(c.cityStateZip)}</p>
        <p>${esc(c.phone)} · ${esc(c.email)}</p>
      </div>
      <div class="badge">
        <div class="label">Receipt</div>
        <div class="paid">Paid</div>
      </div>
    </div>
    <div class="meta">
      <div><div class="k">Receipt / Invoice #</div><b>${number}</b></div>
      <div><div class="k">Date Paid</div><b>${paid}</b></div>
      ${billedTo ? `<div><div class="k">Billed To</div><b>${billedTo}</b></div>` : ""}
    </div>
    <table>
      <thead><tr><th>Description</th><th class="r">Amount</th></tr></thead>
      <tbody><tr><td>${description}</td><td class="r">${amount}</td></tr></tbody>
      <tfoot><tr><td class="r">Total Paid</td><td class="r">${amount}</td></tr></tfoot>
    </table>
    <div class="foot">
      <div>Reference ID: ${id}</div>
      <div>${esc(siteConfig.icrcLine)}</div>
      <div>Thank you for your payment. This receipt was generated by the ABCAC Member Portal.</div>
    </div>
  </div>
  </body></html>`;
}

/** Renders a "Download Receipt" button that opens a clean, branded printable
 *  receipt and triggers the browser's print-to-PDF dialog. */
export function ReceiptDownload({
  receipt,
  label = "Download Receipt",
  size = "sm",
  variant = "outline",
}: {
  receipt: ReceiptData;
  label?: string;
  size?: "sm" | "default" | "lg";
  variant?: "primary" | "outline" | "ghost" | "accent";
}) {
  return (
    <Button variant={variant} size={size} onClick={() => openPrint(buildReceiptHtml(receipt))}>
      {label}
    </Button>
  );
}
