import Link from "next/link";
import { notFound } from "next/navigation";
import { TestingRequestActions } from "@/components/admin/testing-request-actions";
import { ViewFileButton } from "@/components/view-file-button";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { testingStatusLabel } from "@/lib/testing-requests";

export const dynamic = "force-dynamic";

function Detail({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</dt><dd className="mt-1 text-sm font-medium text-ink">{value || "—"}</dd></div>; }

export default async function AdminTestingDetail({ params }: { params: { id: string } }) {
  const sb = createSupabaseServerClient();
  const { data: request } = await sb.from("testing_requests").select("*").eq("id", params.id).maybeSingle();
  if (!request) notFound();
  const supportingDocuments = Array.isArray(request.supporting_documents) ? request.supporting_documents as { name: string; path: string }[] : [];
  return <><Link href="/admin/testing" className="text-sm font-semibold text-brand">← Exam queue</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{request.exam_code} Pre-Registration</h1><p className="mt-1 text-muted">{request.tester_first_name} {request.tester_last_name} · {testingStatusLabel(request.status)}</p></div><span className="rounded-full bg-brand/10 px-3 py-1.5 text-xs font-semibold text-brand">{request.payment_status === "paid" ? "Paid" : "Payment pending"}</span></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_0.75fr]"><div className="space-y-6"><section className="rounded-2xl border border-line bg-surface p-6"><h2 className="text-xl">Tester details</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Detail label="Legal name" value={`${request.tester_first_name} ${request.tester_last_name}`} /><Detail label="Email" value={<a className="text-brand" href={`mailto:${request.tester_email}`}>{request.tester_email}</a>} /><Detail label="Date of birth" value={request.tester_date_of_birth} /><Detail label="Address matching ID" value={request.tester_address} /><Detail label="Exam" value={request.exam_code} /><Detail label="Mode" value={request.testing_mode === "remote" ? "Remote proctored" : "In person"} /><Detail label="Preferred location" value={request.testing_location} /><Detail label="AZBBHE approved" value={request.azbbhe_approved ? "Yes" : "No / certification path"} /></dl></section><section className="rounded-2xl border border-line bg-surface p-6"><h2 className="text-xl">Request details</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Detail label="ABCAC credential" value={request.seeks_abcac_credential ? request.credential_level : "No"} /><Detail label="Accommodations" value={request.accommodations_requested ? (request.accommodations_detail || "Requested — see accommodations form") : "Not requested"} /><Detail label="Paying for another tester" value={request.paying_for_other ? "Yes" : "No"} /><Detail label="Stripe session" value={request.stripe_session_id} /><Detail label="Purchaser" value={`${request.purchaser_first_name} ${request.purchaser_last_name}`} /><Detail label="Purchaser contact" value={`${request.purchaser_email} · ${request.purchaser_phone}`} /></dl>{supportingDocuments.length > 0 && <div className="mt-6 border-t border-line pt-5"><h3 className="text-base">Supporting documents</h3><ul className="mt-3 space-y-2">{supportingDocuments.map((document) => <li key={document.path} className="flex items-center justify-between gap-3 rounded-xl bg-bg px-4 py-3 text-sm"><span className="truncate">{document.name}</span><ViewFileButton bucket="member-documents" path={document.path} /></li>)}</ul></div>}</section></div><TestingRequestActions id={request.id} status={request.status} initialReference={request.smt_candidate_id} initialNote={request.admin_notes} /></div></>;
}
