import type { NativeFormSchema } from "@/lib/native-schemas/types";

// Native schema for the ABCAC Certified Peer Recovery Specialist (CPRS)
// application manual. Reproduces the original PDF application; page numbers
// reference the source PDF for admin review.

export const INITIAL_CPRS_SCHEMA: NativeFormSchema = {
  formKey: "initial-cprs",
  intro: {
    title: "Application for Certified Peer Recovery Specialist (CPRS)",
    paragraphs: [
      "The Certified Peer Recovery Specialist (CPRS) credential is designed for individuals with personal, lived experience in their own recovery or experience as a family member or loved one. The role of the CPRS reflects a collaborative and strengths-based approach, with the primary goal of assisting individuals and family members in achieving sustained recovery from the effects of addiction and/or mental health issues. CPRSs are not clinicians; the peer is not a sponsor, case manager or a therapist but rather a role model, mentor, advocate and motivator.",
      "ABCAC is a member of the International Certification Reciprocity Consortium / Alcohol and Other Drug Abuse (IC&RC / AODA). Certification encompasses two calendar years and may be recertified. Applicants can email or mail questions to ABCAC, P.O. Box 83165 Phoenix, Arizona 85071, phone 480-980-1770, email abcac@abcac.org.",
      "Please type or print only. If there are any problems with the application, you will be notified. Keep a copy of the entire application for your records.",
    ],
  },
  sections: [
    {
      id: "directions-checklist",
      title: "Directions / Checklist",
      description: "Upload the following supporting documentation in the Documents section of your portal before submitting.",
      pdfPage: 2,
      notes: [
        "Documentation of high school diploma/GED or official transcript required, sent directly from the college/university to the ABCAC.",
        "Certificates of attendance for trainings.",
        "Current job description signed and dated by applicant and supervisor.",
        "Previous relevant employment documentation (if needed). Acceptable documentation includes a letter (on company letterhead) from previous employer(s) verifying your duties and dates employed.",
        "Sign and date the ABCAC Certified Peer Recovery Specialist Code of Ethical Conduct (included in this form).",
        "Supervision form completed and signed by supervisor (included in this form).",
        "If you have ever received any disciplinary action from another certification or licensing authority, include a letter of explanation with your application and any relevant documentation.",
        "If you have ever been convicted of a felony, include a letter of explanation with your application and any relevant documentation.",
        "The application fee is $200, payable by check or money order made out to ABCAC. This includes the application manual, testing, and processing fees.",
      ],
    },
    {
      id: "requirements",
      title: "Requirements for CPRS",
      pdfPage: 3,
      notes: [
        "Employment: 500 hours of supervised volunteer or paid practical experience specific to the domains. Volunteer and part-time experience is acceptable if provided under direct supervision; time spent in a supervised substance abuse internship or practicum may be applied. Supervised work experience must be in the four CPRS domains.",
        "Supervision: 25 hours of supervision specific to the domains, provided by an organization’s documented and qualified supervisory staff per job description.",
        "Education: High school diploma/GED, plus 46 hours of education relevant to the domains — ten (10) specific to Advocacy, ten (10) specific to Mentoring/Education, ten (10) specific to Recovery/Wellness Support and 16 specific to Ethical Responsibility. Education is formal, structured instruction (workshops, seminars, institutes, in-services, college/university credit courses and ABCAC approved distance education). There is no limit to the amount of distance learning/online education that can be submitted. Three college credits are equivalent to 45 hours. Education the applicant provides to others may also be used if verified in writing by the sponsoring school or agency.",
        "Examination: Pass the IC&RC Peer Recovery Specialist Examination.",
        "Other: Signed and dated ABCAC Peer Recovery Specialist Code of Ethical Conduct statement; current job description dated and signed by supervisor and applicant; applicant must either live or work at least 51% for a year in Arizona at the time of application.",
        "Certified Peer Recovery Domains: 1. Advocacy, 2. Mentoring/Education, 3. Recovery/Wellness Support, 4. Ethical Responsibility.",
      ],
    },
    {
      id: "fees-and-examination",
      title: "Fees, Examination and Recertification",
      pdfPage: 4,
      notes: [
        "Fees: Test $150; Retest $150; Application Manual $50; Re-certification $100.",
        "Examination: This credential requires successful completion of an IC&RC exam, offered as an on-demand computer based exam administered at approved testing sites in Phoenix or Flagstaff. Candidates may register for the exam after application approval.",
        "Special situations: Individuals with disabilities and/or religious obligations that require modifications in exam administration may request specific procedure changes, in writing, to ABCAC no fewer than 60 days prior to the scheduled exam date, with official documentation.",
        "Cancellation/Rescheduling: Individuals who cancel or do not show up for their test must pay again in order to take the test, unless extenuating circumstances are communicated, approved by ABCAC, and documented.",
        "Retest: Candidates failing the exam can retest after a 60 day wait period from the date of last taking the exam and must pay each time.",
        "Recertification is required every two years and requires a current valid ABCAC certificate, 20 hours of ABCAC approved continuing education (including six (6) hours in professional ethics and responsibilities and three (3) hours of cultural diversity within the two year cycle), reaffirmation of the Code of Ethical Conduct, a re-certification application, and the $100 re-certification fee.",
        "Lapsed certification: A credential is valid for a two year period. If your credential lapses, you have 12 months from your expiration date to recertify, with a $10 per month late fee for each month after expiration. After 12 months you must re-apply and complete all requirements for initial certification.",
        "Appeals: A letter requesting an appeal must be made to ABCAC in writing within 30 days of notification of the board’s action; the Executive Committee will review the entire application and notify the applicant in writing of its findings.",
      ],
    },
    {
      id: "applicant-information",
      title: "Application for Certified Peer Recovery Specialist",
      description: "Please type or print only.",
      pdfPage: 6,
      fields: [
        { id: "application-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "date-of-birth", label: "Date of Birth", type: "date", required: true, span: "half" },
        { id: "applicant-name", label: "Name", type: "text", required: true, span: "full", hint: "Please print your name as it should appear on your certificate." },
        { id: "home-address", label: "Home Address", type: "text", required: true, span: "full" },
        { id: "home-city", label: "City", type: "text", required: true, span: "third" },
        { id: "home-state", label: "State", type: "text", required: true, span: "third" },
        { id: "home-zip", label: "Zip", type: "text", required: true, span: "third" },
        { id: "home-county", label: "County", type: "text", span: "third" },
        { id: "home-phone", label: "Home Phone", type: "text", span: "third" },
        { id: "email", label: "Email", type: "text", required: true, span: "third" },
        { id: "employer", label: "Employer", type: "text", span: "half" },
        { id: "position-title", label: "Position/Title", type: "text", span: "half" },
        { id: "employer-city", label: "Employer City", type: "text", span: "third" },
        { id: "employer-state", label: "Employer State", type: "text", span: "third" },
        { id: "employer-zip", label: "Employer Zip", type: "text", span: "third" },
        { id: "work-phone", label: "Work Phone", type: "text", span: "half" },
        { id: "work-phone-ext", label: "Ext", type: "text", span: "half" },
        { id: "dates-employed", label: "Dates Employed", type: "text", span: "half" },
        { id: "hours-per-week", label: "Hours per Week", type: "text", span: "half" },
        { id: "supervisor-name", label: "Immediate Supervisor", type: "text", span: "half" },
        { id: "supervisor-title", label: "Title", type: "text", span: "half" },
        { id: "supervisor-phone", label: "Supervisor Phone", type: "text", span: "half" },
        { id: "supervisor-email", label: "Supervisor Email", type: "text", span: "half" },
        { id: "college-university", label: "College/University", type: "text", span: "half" },
        { id: "name-on-transcript", label: "Name on Transcript", type: "text", span: "half" },
        { id: "why-pursuing", label: "Why are you pursuing certification?", type: "textarea", required: true, span: "full" },
      ],
    },
    {
      id: "supervisor-attestation-51",
      title: "Supervisor Attestation of Position",
      description: "I hereby attest that the applicant is working in a position where a minimum of 51% of his/her time is spent serving individuals in the recovery process by supporting them in accessing community-based resources, implementing recovery/wellness plans, navigating state and local systems (including addiction and mental health treatment systems) and providing recovery support services. The applicant coaches service recipients to help them develop a strong foundation in recovery (e.g. establishing support systems, self-care, independence/self-sufficiency, healthy coping skills and other skills) that support long-term recovery.",
      pdfPage: 6,
      signerSection: { role: "Supervisor" },
      fields: [
        { id: "position-attestation-signature", label: "Supervisor’s Signature", type: "signature", span: "full" },
      ],
    },
    {
      id: "background-credentials",
      title: "Background Information — Credentials Held",
      pdfPage: 7,
      fields: [
        { id: "background-held-other-state", label: "Do you hold, or have you ever held licensure, certification, or registration in any other state?", type: "yesno", required: true, span: "full", hint: "If yes, complete the credential table below." },
      ],
      table: {
        id: "background-credentials-table",
        columns: [
          { id: "credential-title", label: "Title of Credential", width: "wide" },
          { id: "state", label: "State", width: "narrow" },
          { id: "date-issued", label: "Date Issued", width: "narrow" },
          { id: "current-status", label: "Current Status", width: "narrow" },
        ],
        rows: 5,
      },
    },
    {
      id: "background-questions",
      title: "Background Information",
      pdfPage: 7,
      fields: [
        { id: "background-association-certificate", label: "Do you hold a certificate through a behavioral health professional association?", type: "yesno", required: true, span: "full", detailLabel: "If yes, give professional credential held" },
        { id: "background-denied", label: "Have you ever applied for and been denied a license, certificate or registration in any behavioral health profession?", type: "yesno", required: true, span: "full" },
        { id: "background-disciplined", label: "Have you ever had any disciplinary action taken against you by the authority issuing the license, certificate or registration in any behavioral health profession?", type: "yesno", required: true, span: "full" },
        { id: "background-surrendered", label: "Have you ever surrendered or canceled your license, certification or registration in lieu of disciplinary proceedings by the issuing authority in any behavioral health profession?", type: "yesno", required: true, span: "full" },
        { id: "background-association-discipline", label: "Have you ever been the subject of a disciplinary action by a regulatory committee of a professional association?", type: "yesno", required: true, span: "full" },
        { id: "background-convicted", label: "Have you ever been convicted or pled guilty or pled no contest to a criminal offense?", type: "yesno", required: true, span: "full" },
        { id: "background-malpractice", label: "Have you ever been the defendant in a malpractice suit, and either entered into a settlement agreement or paid court-awarded damages, or is there such a suit pending?", type: "yesno", required: true, span: "full" },
        { id: "background-terminated", label: "Have you ever been involuntarily terminated from any behavioral health or related employment for unprofessional conduct?", type: "yesno", required: true, span: "full" },
        { id: "background-explanation", label: "If the answers to any of these questions are YES, please explain", type: "textarea", span: "full", hint: "Enclose any relevant documents in the Documents section of your portal." },
        { id: "background-name", label: "Name", type: "text", required: true, span: "half" },
        { id: "background-date", label: "Date", type: "date", required: true, span: "half" },
      ],
    },
    {
      id: "previous-employment",
      title: "Previous Relevant Employment, if Applicable",
      pdfPage: 8,
      notes: [
        "Include a letter (on company letterhead) from each previous employer verifying your duties and dates employed. Upload these letters in the Documents section of your portal.",
      ],
      table: {
        id: "previous-employment-table",
        columns: [
          { id: "employer-name", label: "Name of Employer", width: "wide" },
          { id: "address", label: "Address", width: "wide" },
          { id: "phone", label: "Phone", width: "narrow" },
          { id: "title", label: "Your Title", width: "narrow" },
          { id: "hours-per-week", label: "Hours per Week", width: "narrow" },
          { id: "dates-employed", label: "Dates Employed", width: "narrow" },
          { id: "supervisor", label: "Immediate Supervisor", width: "wide" },
        ],
        rows: 5,
      },
    },
    {
      id: "supervision",
      title: "Supervision",
      description: "To Supervisor: Please complete this form indicating the applicant’s on-the-job supervision. This form is not intended to document the applicant’s total number of hours worked but rather the hours of on-the-job supervision you have provided the applicant. Supervision is a formal or informal process that is administrative, evaluative, clinical, and supportive. It can be provided by more than one person, it ensures quality of clinical care, and extends over time. Supervision includes observation, mentoring, coaching, evaluating, inspiring, and creating an atmosphere that promotes self-motivation, learning, and professional development. In all aspects of the supervision process, ethical and diversity issues must be in the forefront.",
      notes: [
        "I hereby attest that a minimum of 25 hours of supervision in the domains have been attained by the above-named applicant. The total must be at least 25 hours.",
      ],
      pdfPage: 9,
      signerSection: { role: "Supervisor" },
      fields: [
        { id: "supervision-applicant-name", label: "Applicant’s Name", type: "text", span: "full" },
      ],
      table: {
        id: "supervision-hours-table",
        columns: [
          { id: "domain", label: "CPRS Domains", width: "wide" },
          { id: "hours", label: "# of Hours Received in Each", width: "narrow" },
        ],
        rows: 5,
        fixedFirstColumn: [
          "1. Advocacy",
          "2. Mentoring/Education",
          "3. Recovery/Wellness Support",
          "4. Ethical Responsibility",
          "TOTAL (must be at least 25 hours)",
        ],
      },
    },
    {
      id: "supervision-signoff",
      title: "Supervisor Comments and Signature",
      pdfPage: 9,
      signerSection: { role: "Supervisor" },
      fields: [
        { id: "supervision-comments", label: "Please provide comments regarding the applicant’s performance", type: "textarea", span: "full" },
        { id: "supervision-supervisor-signature", label: "Supervisor’s Signature", type: "signature", span: "half" },
        { id: "supervision-signature-date", label: "Date", type: "date", span: "half" },
      ],
    },
    {
      id: "code-of-ethics",
      title: "ABCAC Certified Peer Recovery Specialist Code of Ethical Conduct",
      description: "Read the full Code of Ethical Conduct below, then sign the acknowledgment in the next section.",
      pdfPage: 10,
      notes: [
        "Unlawful Conduct (Rules 1.1–1.2): Once certified, a certified professional shall not be cited, arrested, or convicted for any offense relating to their ability to provide substance abuse and other behavioral health services or that reflects conduct unbecoming a certified professional, and shall not be convicted of any crime that involves the use of any controlled or psychoactive substance.",
        "Sexual Misconduct (Rules 2.1–2.4): A certified professional shall under no circumstances engage in sexual activities or sexual contact with clients (consensual or forced), with clients’ relatives or close personal relations where there is risk of exploitation, or with former clients, and shall not provide clinical services to individuals with whom they have had a prior sexual relationship.",
        "Fraud-Related Conduct (Rules 3.1–3.7): A certified professional shall not present false or fraudulent claims or documents; shall not use misrepresentation in the procurement of certification or recertification (including misrepresentation of qualifications, education, certification, accreditation, affiliations, employment experience, plagiarism of application materials, or falsification of references); shall not use titles or credentials to which they are not entitled; shall not provide service under a false name; shall not sign or issue documents known to contain false or misleading statements; shall not create false, deceptive, or misleading advertisements; and must acknowledge and document materials, techniques and people used in professional publications, respecting copyright.",
        "Exploitation of Clients (Rules 4.1–4.7): A certified professional shall not develop exploitative relationships with clients or their family members; shall not misappropriate property; shall not enter relationships involving financial gain from services or goods unrelated to the provision of services; shall not promote any treatment, procedure, product, or service for personal gain; shall not ask for nor accept gifts or favors from clients or their family members; shall not offer, give, or receive remuneration for client referrals; and shall not accept fees or gratuities for professional work a person is entitled to through the professional’s institution or agency.",
        "Professional Standards (Rules 5.1–5.9): A certified professional shall not participate in discrimination on any basis; must seek therapy (or request inactive status) for any impairment that interferes with professional functioning; shall comply with all terms of a certification or license; shall meet generally accepted standards of practice; shall not perform services outside their area of training, expertise, competence, or scope of practice; shall not reveal confidential information without prior written consent except as authorized or required by law; shall not permit publication of photographs, client names or records without requisite releases; shall not abandon clients without appropriate closure of services; and shall obtain appropriate consultation or referral when a client’s problem is beyond their scope.",
        "Safety & Welfare (Rules 6.1–6.2): A certified professional shall not use any psychoactive substance in a manner dangerous or injurious to a recipient of services or others, or that impairs their ability to safely and competently provide services. All certified professionals are mandated child abuse reporters.",
        "Record Keeping (Rule 7.1): A certified professional shall not falsify, amend, or knowingly make incorrect entries or fail to make timely essential entries into the client record.",
        "Assisting Unqualified/Unlicensed Practice (Rule 8.1): A certified professional shall not refer a client to a person that he/she knows or should have known is not qualified by training, experience, certification, or license to perform the delegated professional responsibility.",
        "Discipline in Other Jurisdictions (Rule 9.1): A certified professional whose certification or license from any authority has been suspended, revoked, placed on probation, or otherwise restricted or disciplined shall promptly alert the Board of such disciplinary action.",
        "Cooperation with the Board (Rules 10.1–10.6): A certified professional shall cooperate in any investigation and shall not interfere with an investigation or disciplinary proceeding (including misrepresentation of facts, threats, harassment, inducements, refusing to accept or respond to a letter of complaint, or allowing a credential to lapse or attempting to resign it while an ethics complaint is pending); shall not make false statements to ABCAC or any disciplinary authority; shall alert colleagues to potentially unethical behavior and report uncorrected violations within 90 days; shall cooperate with ABCAC investigations when they have firsthand knowledge; shall not file complaints known to be false or misleading; and shall comply with client-information disclosure requirements when submitting information to ABCAC.",
      ],
    },
    {
      id: "ethics-acknowledgment",
      title: "Code of Ethical Conduct Acknowledgment",
      description: "I have read the entire ABCAC Certified Peer Recovery Specialist Code of Ethical Conduct and subscribe to it.",
      pdfPage: 13,
      fields: [
        { id: "ethics-signature", label: "Signature", type: "signature", required: true, span: "half" },
        { id: "ethics-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "ethics-printed-name", label: "Printed Name", type: "text", required: true, span: "half" },
      ],
    },
    {
      id: "release",
      title: "Release",
      description: "I hereby request that ABCAC grant the credential to me based on the following assurances and documentation:",
      pdfPage: 14,
      notes: [
        "I subscribe to and commit myself to professional conduct in keeping with the ABCAC Certified Peer Recovery Specialist Code of Ethical Conduct.",
        "I hereby certify that the information given herein is true and complete to the best of my knowledge and belief. I also authorize any necessary investigation and the release of manuscripts and other personal information relative to my certification. Falsification of any records or documents in my application will nullify this application and will result in denial or revocation of certification.",
        "I consent to the release of information contained in my application and any other pertinent data submitted to or collected by ABCAC to officers, members, and staff of the aforementioned Board.",
        "I consent to authorize ABCAC to gather information from third parties regarding continuing education and employment and understand that such communication shall be treated as confidential.",
        "Allegations of ethical misconduct reported to ABCAC before, during, or after application for certification is made will be investigated by ABCAC and could result in the nullification of the application or denial or revocation of certification.",
      ],
      fields: [
        { id: "release-signature", label: "Signature", type: "signature", required: true, span: "half", hint: "I declare under penalty of perjury that all information I have provided is true and correct." },
        { id: "release-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "release-printed-name", label: "Printed Name", type: "text", required: true, span: "half" },
      ],
    },
  ],
};
