import type { NativeFormSchema } from "@/lib/native-schemas/types";

// Native schema for the ABCAC Peer Recovery Associate (PR-A) application
// manual, transcribed verbatim from PRA-Application-Manual-2.docx (uploaded
// by ABCAC). Page numbers reference the generated public/forms/library/
// initial-pra.pdf (see scripts/build-pra-manual-pdf.mjs), which mirrors this
// same content 1:1.

export const INITIAL_PRA_SCHEMA: NativeFormSchema = {
  formKey: "initial-pra",
  intro: {
    title: "Application for Peer Recovery Associate (PR-A)",
    paragraphs: [
      "The Peer Recovery Associate (PR-A) credential is offered by the Arizona Board for Certification of Addiction Counselors (ABCAC) in partnership with the International Certification & Reciprocity Consortium (IC&RC). This credential is designed for individuals who have personal lived experience with mental health and/or substance use conditions and who wish to provide peer support services in the state of Arizona.",
      "Peer Recovery Associates serve as a critical bridge between people in recovery and the behavioral health system. They offer hope, guidance, and connection to resources through the unique power of shared lived experience. The PR-A credential is recognized across all IC&RC member boards.",
      "Applicants can email or mail questions to ABCAC, PO Box 83165, Phoenix, Arizona 85071, phone 480-980-1770, email abcacb@abcac.org.",
    ],
  },
  sections: [
    {
      id: "criteria",
      title: "Application Criteria",
      description: "To qualify for the Peer Recovery Associate credential, applicants must meet ALL of the following requirements. Documentation for each requirement must be submitted with the completed application.",
      pdfPage: 2,
      notes: [
        "1. Lived Experience — the applicant must have personal lived experience with a mental health and/or substance use condition and must demonstrate how that experience informs their peer support work. Lived experience must be described and attested on Form B (Lived Experience Attestation).",
        "2. Training — a minimum of 40 hours of training through an AHCCCS-recognized Peer Support Employment Training Program, covering the four IC&RC PR-A practice domains: (1) Advocacy, (2) Education & Support, (3) Community Resources, and (4) Professional Responsibility. A minimum of 6 hours must specifically address ethics.",
        "3. Examination — the applicant must pass the board-approved examination administered through their AHCCCS-recognized Peer Support Employment Training Program (not administered through a third-party testing center).",
        "4. Supervision Agreement — a completed Supervision Agreement (Form C) identifying a qualified supervisor, signed by both the applicant and the supervisor. Supervised practice hours shall not exceed 120 hours for purposes of the PR-A application.",
        "5. Code of Ethics — the applicant must sign the ABCAC Code of Ethics Affirmation (Form A), affirming they will abide by the NAADAC Ethical Standards (Principles 1–12) and the peer-specific ethical principles adopted by ABCAC.",
        "6. Application Fee — a non-refundable application fee of $150.00 (check or money order payable to ABCAC; ABCAC does not accept cash).",
        "7. Arizona Residency / Jurisdiction — a minimum of 51% of the applicant's peer support professional activities must occur within Arizona.",
      ],
    },
    {
      id: "checklist",
      title: "Certification Application Checklist",
      description: "Complete all items below before submitting your application to ABCAC. Incomplete applications will not be processed. Upload supporting documentation in the Documents section of your portal.",
      pdfPage: 3,
      notes: [
        "Completed Application for Certification (this packet — all pages, fully completed and signed).",
        "Form A — Code of Ethics Affirmation (signed by applicant).",
        "Form B — Lived Experience Attestation (signed by applicant).",
        "Form C — Supervision Agreement (signed by both applicant and supervisor).",
        "Training Documentation — certificate or letter confirming 40 hours from an AHCCCS-recognized Peer Support Employment Training Program.",
        "Examination Documentation — certificate or letter confirming passing score from the training provider.",
        "Application Fee — non-refundable $150.00 (payable at checkout, or by check/money order to ABCAC).",
      ],
    },
    {
      id: "applicant-information",
      title: "Section A — Applicant Information",
      description: "Application for Certification — Peer Recovery Associate (PR-A). Please type or print only.",
      pdfPage: 4,
      fields: [
        { id: "last-name", label: "Last Name", type: "text", required: true, span: "third" },
        { id: "first-name", label: "First Name", type: "text", required: true, span: "third" },
        { id: "middle-initial", label: "Middle Initial", type: "text", span: "third" },
        { id: "preferred-name", label: "Preferred Name (if different)", type: "text", span: "half" },
        { id: "date-of-birth", label: "Date of Birth", type: "date", required: true, span: "half" },
        { id: "street-address", label: "Current Street Address", type: "text", required: true, span: "full" },
        { id: "city", label: "City", type: "text", required: true, span: "third" },
        { id: "state", label: "State", type: "text", required: true, span: "third" },
        { id: "zip", label: "ZIP Code", type: "text", required: true, span: "third" },
        { id: "home-phone", label: "Home Phone", type: "text", span: "half" },
        { id: "cell-phone", label: "Cell Phone", type: "text", span: "half" },
        { id: "email", label: "Email Address", type: "text", required: true, span: "full" },
        { id: "drivers-license-number", label: "Driver's License Number", type: "text", span: "half" },
        { id: "drivers-license-state", label: "State of Issuance", type: "text", span: "half" },
      ],
    },
    {
      id: "training-examination",
      title: "Section B — Training & Examination",
      pdfPage: 4,
      fields: [
        { id: "training-program-name", label: "Name of AHCCCS-Recognized Peer Support Employment Training Program", type: "text", required: true, span: "full" },
        { id: "training-provider", label: "Training Provider / Organization", type: "text", required: true, span: "full" },
        { id: "training-start-date", label: "Training Start Date", type: "date", span: "third" },
        { id: "training-end-date", label: "Training End Date", type: "date", span: "third" },
        { id: "training-total-hours", label: "Total Hours Completed", type: "text", required: true, span: "third", hint: "Must be 40 or more." },
        { id: "exam-date", label: "Examination Date", type: "date", span: "half" },
        { id: "exam-result", label: "Examination Result (Pass/Fail)", type: "text", required: true, span: "half" },
        { id: "exam-administrator", label: "Name of Person / Organization Administering Examination", type: "text", span: "full" },
      ],
    },
    {
      id: "employment-practice",
      title: "Section C — Current Employment / Practice Setting",
      pdfPage: 4,
      fields: [
        { id: "employer", label: "Current Employer / Agency", type: "text", span: "full" },
        { id: "employer-address", label: "Employer Address", type: "text", span: "full" },
        { id: "job-title", label: "Job Title", type: "text", span: "half" },
        { id: "job-start-date", label: "Start Date", type: "date", span: "half" },
        { id: "employer-supervisor-name", label: "Supervisor Name", type: "text", span: "half" },
        { id: "employer-supervisor-phone", label: "Supervisor Phone", type: "text", span: "half" },
        { id: "employer-supervisor-email", label: "Supervisor Email", type: "text", span: "half" },
        { id: "hours-per-week", label: "Hours Per Week in Peer Support Role", type: "text", span: "half" },
        { id: "percent-arizona", label: "% of Practice in Arizona", type: "text", required: true, span: "half", hint: "Must be at least 51%." },
      ],
    },
    {
      id: "background-information",
      title: "Section D — Background Information",
      description: "Answer all questions truthfully. If you answer YES to any question, provide a full written explanation and attach it in the Documents section of your portal.",
      pdfPage: 5,
      fields: [
        { id: "background-other-credentials", label: "Do you currently hold any other professional certifications or credentials in behavioral health, addiction counseling, or peer support?", type: "yesno", required: true, span: "full" },
        { id: "background-held-other-state", label: "Have you ever held a behavioral health certification, license, or credential in Arizona or any other state?", type: "yesno", required: true, span: "full" },
        { id: "background-denied", label: "Has a certification, license, or credential application ever been denied, withdrawn, or rejected by any board or organization?", type: "yesno", required: true, span: "full" },
        { id: "background-disciplined", label: "Has any disciplinary action ever been taken against a certification, license, or credential you hold or held?", type: "yesno", required: true, span: "full" },
        { id: "background-surrendered", label: "Have you ever voluntarily surrendered a certification, license, or credential while under investigation or to avoid disciplinary action?", type: "yesno", required: true, span: "full" },
        { id: "background-under-investigation", label: "Are you currently under investigation by any professional regulatory body, certifying organization, or licensing board?", type: "yesno", required: true, span: "full" },
        { id: "background-convicted", label: "Have you ever been convicted of a crime (felony or misdemeanor), pled guilty or no contest, or had a conviction expunged or set aside?", type: "yesno", required: true, span: "full" },
        { id: "background-civil-judgment", label: "Has a civil judgment or malpractice claim ever been entered against you in connection with your professional services?", type: "yesno", required: true, span: "full" },
        { id: "background-terminated", label: "Have you ever been involuntarily terminated from employment for reasons related to professional conduct, substance use, or client safety?", type: "yesno", required: true, span: "full" },
        { id: "background-explanation", label: "If the answer to any question above is YES, provide a full written explanation", type: "textarea", span: "full" },
      ],
    },
    {
      id: "residency-certification",
      title: "Section E — Arizona Residency & Jurisdiction Certification",
      description: "I certify that I am a resident of the state of Arizona and that the primary location of my peer support practice is within Arizona. I further certify that at least 51% of my professional peer support activities occur within the state of Arizona.",
      pdfPage: 6,
      fields: [
        { id: "residency-signature", label: "Applicant Signature", type: "signature", required: true, span: "half" },
        { id: "residency-date", label: "Date", type: "date", required: true, span: "half" },
      ],
    },
    {
      id: "release-authorization",
      title: "Section F — Release and Authorization",
      description: "I authorize ABCAC to investigate all information provided in this application, and authorize all persons and organizations to release information requested by ABCAC in connection with this application. I understand that submission of false, fraudulent, or misleading information is grounds for denial, suspension, or revocation of certification. I attest that all information provided is true, accurate, and complete to the best of my knowledge.",
      pdfPage: 6,
      fields: [
        { id: "release-signature", label: "Applicant Signature", type: "signature", required: true, span: "half" },
        { id: "release-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "release-printed-name", label: "Printed Name", type: "text", required: true, span: "half" },
        { id: "release-current-credentials", label: "Current Credential(s) / Title (if any)", type: "text", span: "half" },
      ],
    },
    {
      id: "form-a-code-of-ethics",
      title: "Form A — Code of Ethics Affirmation",
      description: "As a condition of certification and as a continuing obligation of the Peer Recovery Associate (PR-A) credential, I affirm the following:",
      pdfPage: 7,
      notes: [
        "1. I will abide by the NAADAC Code of Ethics, including all twelve (12) ethical principles, as adopted by ABCAC.",
        "2. I will place the wellbeing, dignity, and recovery of every person I serve above all other considerations in my peer support practice.",
        "3. I will not misrepresent my qualifications, credentials, role, or the scope of peer support services to any person, employer, or agency.",
        "4. I will maintain appropriate boundaries and will not exploit the relationship, vulnerability, or trust of any person I serve.",
        "5. I will hold all information shared with me in the peer support relationship in strict confidence, disclosing only as required by law or with informed consent.",
        "6. I will practice within the scope of the Peer Recovery Associate credential and will refer individuals to licensed or clinical professionals when their needs exceed my role.",
        "7. I will not allow personal recovery, bias, or self-interest to impair my professional judgment or my ability to serve others effectively.",
        "8. I will continue to invest in my own recovery and in the professional development required to serve others with competence and integrity.",
        "9. I will treat all individuals with respect, dignity, and cultural humility, honoring the diversity of recovery paths and lived experience.",
        "10. I will report any violations of ethical standards by peers, colleagues, or supervisors to the appropriate authority as required.",
        "11. I will cooperate fully with any investigation conducted by ABCAC related to my conduct or the conduct of others under this credential.",
        "12. I understand that violation of this Code of Ethics may result in suspension or revocation of my Peer Recovery Associate certification.",
      ],
      fields: [
        { id: "ethics-signature", label: "Applicant Signature", type: "signature", required: true, span: "half", hint: "I affirm that I have read, understand, and agree to be bound by the ABCAC Code of Ethics and the NAADAC Ethical Standards as adopted by ABCAC." },
        { id: "ethics-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "ethics-printed-name", label: "Printed Name", type: "text", required: true, span: "half" },
        { id: "ethics-employer", label: "Employer / Agency", type: "text", span: "half" },
        { id: "ethics-training-program", label: "AHCCCS-Recognized Training Program Completed", type: "text", span: "full" },
      ],
    },
    {
      id: "form-b-lived-experience",
      title: "Form B — Lived Experience Attestation",
      description: "The Peer Recovery Associate credential is grounded in the power of shared lived experience. Your response will be reviewed by ABCAC only and held in strict confidence. You are not required to disclose specific diagnoses, substances, or treatment history — only to confirm lived experience and describe how it shapes your peer support practice.",
      pdfPage: 8,
      fields: [
        { id: "lived-experience-name", label: "Applicant Name (Printed)", type: "text", required: true, span: "half" },
        { id: "lived-experience-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "lived-experience-part1", label: "Part 1 — Lived Experience: describe your personal experience with a mental health and/or substance use condition and the challenges you have faced and overcome", type: "textarea", required: true, span: "full" },
        { id: "lived-experience-part2", label: "Part 2 — Connection to Peer Support Work: explain how your lived experience informs your ability to support others in their recovery journey", type: "textarea", required: true, span: "full" },
        { id: "lived-experience-signature", label: "Applicant Signature", type: "signature", required: true, span: "half", hint: "I attest that the information provided is truthful and accurately describes my lived experience." },
        { id: "lived-experience-signature-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "lived-experience-printed-name", label: "Printed Name", type: "text", required: true, span: "half" },
      ],
    },
    {
      id: "form-c-applicant",
      title: "Form C — Supervision Agreement (Applicant)",
      description: "All applicants for the Peer Recovery Associate credential must have a qualified supervisor identified and agree to the terms of supervision described in this form. This agreement must be signed by both the applicant and the supervisor and submitted with the application.",
      pdfPage: 9,
      fields: [
        { id: "supervision-applicant-name", label: "Applicant Name", type: "text", required: true, span: "half" },
        { id: "supervision-applicant-date", label: "Date", type: "date", span: "half" },
        { id: "supervision-applicant-employer", label: "Employer / Agency", type: "text", span: "half" },
        { id: "supervision-applicant-title", label: "Job Title / Role", type: "text", span: "half" },
        { id: "supervision-applicant-phone", label: "Phone", type: "text", span: "half" },
        { id: "supervision-applicant-email", label: "Email", type: "text", span: "half" },
        { id: "supervision-start-date", label: "Supervision Start Date", type: "date", span: "third" },
        { id: "supervision-anticipated-hours", label: "Anticipated Hours of Supervision", type: "text", span: "third", hint: "Supervised practice hours shall not exceed 120 hours." },
        { id: "supervision-method", label: "Method of Supervision (individual, group, combination)", type: "text", span: "third" },
        { id: "supervision-frequency", label: "Frequency of Supervision Sessions", type: "text", span: "full" },
        { id: "supervision-applicant-signature", label: "Applicant Signature", type: "signature", required: true, span: "half" },
        { id: "supervision-applicant-signature-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "supervision-applicant-printed-name", label: "Printed Name", type: "text", required: true, span: "half" },
      ],
    },
    {
      id: "form-c-supervisor",
      title: "Form C — Supervision Agreement (Supervisor)",
      description: "By signing below, the supervisor agrees to provide oversight, guidance, and support to the applicant in accordance with the standards of the Peer Recovery Associate credential, to be available for scheduled supervision sessions, and to document supervision hours as required by ABCAC.",
      pdfPage: 9,
      signerSection: { role: "Supervisor" },
      fields: [
        { id: "supervisor-name", label: "Supervisor Name", type: "text", required: true, span: "half" },
        { id: "supervisor-credentials", label: "Credential(s)", type: "text", span: "half" },
        { id: "supervisor-title", label: "Title / Position", type: "text", span: "half" },
        { id: "supervisor-agency", label: "Agency / Organization", type: "text", span: "half" },
        { id: "supervisor-address", label: "Address", type: "text", span: "full" },
        { id: "supervisor-phone", label: "Phone", type: "text", span: "half" },
        { id: "supervisor-email", label: "Email", type: "text", span: "half" },
        { id: "supervisor-signature", label: "Supervisor Signature", type: "signature", span: "half" },
        { id: "supervisor-signature-date", label: "Date", type: "date", span: "half" },
        { id: "supervisor-printed-name", label: "Printed Name", type: "text", span: "half" },
        { id: "supervisor-credential-number", label: "Credential / License Number", type: "text", span: "half" },
      ],
    },
    {
      id: "form-d-training",
      title: "Form D — Training Documentation",
      description: "Document the training hours completed through your AHCCCS-recognized Peer Support Employment Training Program. All 40 hours must be documented. Attach a certificate of completion or a signed letter from the training provider in the Documents section of your portal.",
      pdfPage: 10,
      notes: [
        "IC&RC PR-A Domains: (1) Advocacy, (2) Education & Support, (3) Community Resources, (4) Professional Responsibility.",
      ],
      fields: [
        { id: "form-d-applicant-name", label: "Applicant Name (Printed)", type: "text", required: true, span: "full" },
        { id: "form-d-program", label: "Training Program / Organization", type: "text", required: true, span: "full" },
        { id: "form-d-instructor", label: "Training Program Instructor / Director", type: "text", span: "full" },
        { id: "form-d-start-date", label: "Training Start Date", type: "date", span: "half" },
        { id: "form-d-end-date", label: "Training End Date", type: "date", span: "half" },
        { id: "form-d-total-hours", label: "Total Hours Completed", type: "text", required: true, span: "half", hint: "Must be 40 or more." },
        { id: "form-d-ethics-hours", label: "Ethics Hours Included", type: "text", required: true, span: "half", hint: "Must be 6 or more." },
      ],
      table: {
        id: "training-log-table",
        columns: [
          { id: "course-title", label: "Title of Course / Module", width: "wide" },
          { id: "date-completed", label: "Date Completed", width: "narrow" },
          { id: "hours", label: "Hours", width: "narrow" },
          { id: "domain", label: "IC&RC Domain", width: "narrow" },
          { id: "provider", label: "Training Provider / Instructor", width: "wide" },
        ],
        rows: 8,
      },
    },
    {
      id: "form-d-provider-attestation",
      title: "Form D — Training Provider Attestation",
      description: "I certify that the applicant named above has successfully completed the training hours documented on this form through our AHCCCS-recognized Peer Support Employment Training Program.",
      pdfPage: 10,
      signerSection: { role: "Training Provider" },
      fields: [
        { id: "provider-signature", label: "Provider Signature", type: "signature", span: "half" },
        { id: "provider-signature-date", label: "Date", type: "date", span: "half" },
        { id: "provider-printed-name-title", label: "Printed Name & Title", type: "text", span: "half" },
        { id: "provider-organization", label: "Organization / Program", type: "text", span: "half" },
        { id: "provider-phone", label: "Phone", type: "text", span: "half" },
      ],
    },
  ],
};
