import type { NativeFormSchema } from "@/lib/native-schemas/types";

// Native (HTML) version of the ABCAC Certified Criminal Justice Professional
// (CCJP) application manual. Section pdfPage numbers reference the pages of the
// original PDF packet.

export const INITIAL_CCJP_SCHEMA: NativeFormSchema = {
  formKey: "initial-ccjp",
  intro: {
    title: "Application for Certified Criminal Justice Professional (CCJP)",
    paragraphs: [
      "The Arizona Board for Certification of Addiction Counselors (ABCAC) has designed the CCJP credential for criminal justice professionals who provide treatment services to adult and juvenile alcohol/drug offenders. Individuals seeking this certification must be knowledgeable of both the criminal and substance abuse treatment systems.",
      "The certification process accommodates and evaluates those who are trained experientially as well as those who are academically trained. It defines the core knowledge and skill bases needed by all CCJPs regardless of their professional training, orientation or occupation, so that quality addiction services are available to adult and juvenile substance abuse offenders.",
      "The process of certification requires the completion of the enclosed forms and supporting documentation. Make copies of all documentation. If you have used any names other than the name on this application, please submit legal documentation of a name change along with the application. All materials submitted are considered property of ABCAC and may be disposed of after three (3) years.",
      "Questions? Contact ABCAC: PO Box 83165, Phoenix, AZ 85071 — abcac@abcac.org — (602) 402-7197 — abcac.org.",
    ],
  },
  sections: [
    {
      id: "requirements",
      title: "CCJP Application Requirements",
      pdfPage: 3,
      notes: [
        "Work Experience: 6,000 hours (three years) of supervised, paid (full or part time) or voluntary work experience providing direct service to individuals involved in the criminal justice system. Experience hours must have been obtained within the past 10 years.",
        "Work experience exchanges: an Associates degree in Behavioral Science or a non-reciprocal ADC credential can exchange for 1,000 hours; a BA/BS degree in Behavioral Science or reciprocal ADC credential for 2,000 hours; a Master's degree in Behavioral Science or reciprocal CS credential for 4,000 hours; above a Master's level or reciprocal AADC credential or other advanced credential (NBCC, CRCC, NASW, MAC, etc.) for 5,000 hours.",
        "Education: 270 contact hours of training specifically related to the ICRC/AODA International Certified Criminal Justice Professional (ICCJP) performance domains as they relate to both adults and juveniles, with a minimum of 10 hours in each domain. A High School Diploma is required. 6 hours of criminal justice specific ethics.",
        "Education exchanges: an Associates degree or non-reciprocal ADC credential can exchange for 70 hours; a BA/BS degree in Behavioral Science or reciprocal ADC credential for 120 hours; a Master's degree in Behavioral Science or reciprocal CS credential for 170 hours; above a Master's level or reciprocal AADC credential or other advanced credential may exchange for 190 hours.",
        "Supervision: 200 hours of direct clinical supervision, specific to the domains, with a minimum of 10 hours in each domain. A High School Diploma is required.",
        "Supervision exchanges: an Associates degree or non-reciprocal ADC credential may exchange for 50 hours; a BA/BS degree in Behavioral Science or reciprocal ADC credential for 100 hours; a Master's degree in Behavioral Science or reciprocal CS credential for 140 hours; above a Master's level or IC&RC AADC credential or other advanced credential, no hours are required.",
        "Testing: successful completion of the IC&RC CCJP examination.",
        "Code of Ethics: the applicant must read, agree to, and sign ABCAC's Criminal Justice Code of Ethics. There is a written enforcement and appeals process if a professional violates ABCAC's Code of Ethics.",
        "Recertification: forty (40) hours of continuing education training specifically related to the CCJP performance domains every 2 years, or 20 hours every year of certification. A three (3) hour class on Ethics and a three (3) hour class in Cultural Diversity education must be included in the forty (40) hours of CEUs.",
        "Residency: applicants must live and/or work at least 51% of the time in the jurisdiction of the Arizona Board for Certification of Addiction Counselors (ABCAC) at the time of application.",
      ],
    },
    {
      id: "education-training-rules",
      title: "Education and Training for the CCJP Credential",
      description: "The education/training requirement is a total of 270 contact hours with a minimum of 10 hours in each performance domain, specifically related to the knowledge and skills necessary to perform the tasks within the CCJP performance domains as they relate to both adults and juveniles.",
      pdfPage: 4,
      notes: [
        "All applicants must have completed six (6) hours of education in counseling ethics and four (4) hours of education in HIV/AIDS education. Education is defined as formal, structured instruction in the form of workshops, seminars, institutes, in-services, college/university credit courses and distance learning.",
        "All education hours must be documented. Applicants are responsible for securing and submitting documentation of attendance, the number of contact hours, dates and content description (upload in the Documents section of your portal).",
        "College and university courses specifically related to the CCJP performance domains will be accepted. Credit is not allowed for any audited college courses. One college credit is the equivalent of ten (10) contact hours. Transcripts must be sent directly to ABCAC from the college.",
        "Education events which have received approval by other IC&RC member boards will be accepted.",
        "In-service training relating to the CCJP performance domains may be applied; twenty (20) hours only are allowed.",
        "Home study training (internet, correspondence, teleconferences) may be used for both initial certification and recertification. Twenty five (25) hours of home study contact hours are allowed.",
        "Therapeutic education and attendance at meetings of A.A., Al-Anon, etc., are not applicable for the ICCJP certification.",
        "All education hours submitted will be evaluated by the ABCAC credential committee to determine and validate that they are relevant to the ICCJP credential.",
      ],
    },
    {
      id: "exam-information",
      title: "CCJP IC&RC Exam",
      pdfPage: 5,
      notes: [
        "All Certified Criminal Justice Professional applicants must successfully complete the IC&RC examination.",
        "Individuals with disabilities and/or religious obligations that require modifications in test administration may request specific procedure changes, in writing, to ABCAC sixty (60) days prior to the scheduled test date, with official documentation of the disability or religious issue.",
        "To be eligible for the exam, the application manual must be completed and approved by the ABCAC credential committee. A check or money order for $375.00 made payable to ABCAC must be mailed to ABCAC (PO Box 83165, Phoenix, AZ 85071).",
      ],
    },
    {
      id: "checklist",
      title: "Certification Application Checklist",
      description: "It is the responsibility of the applicant to submit complete documentation (certificates, transcripts, etc.). Please check each item to be certain your application is complete.",
      pdfPage: 6,
      notes: [
        "The application must be completed within one year of applying. After one year has lapsed from the time of application, the applicant must re-apply.",
        "All fees are non-refundable. The $375.00 non-refundable processing fee is payable to the Arizona Board for Certification of Addiction Counselors (ABCAC).",
        "Complete the application form with all questions answered (no blank spaces). Specific rather than general information is needed.",
      ],
      fields: [
        { id: "checklist-application", label: "Application for Certification completed. Copies of certificates from training programs and transcripts of education courses completed are included (upload in the Documents section of your portal).", type: "check", span: "full" },
        { id: "checklist-residency-ethics", label: "Read and signed the Residential Certification and the Code of Ethics provided in this packet.", type: "check", span: "full" },
        { id: "checklist-recommendations", label: "Three letters of recommendation. These letters should attest to your character and competence, and be sent directly to ABCAC by the signer.", type: "check", span: "full" },
        { id: "checklist-fieldwork-log", label: "Supervised Field Work Log for core functions completed.", type: "check", span: "full" },
      ],
    },
    {
      id: "applicant",
      title: "Applicant Information",
      pdfPage: 7,
      fields: [
        { id: "name-last", label: "Name (Last)", type: "text", required: true, span: "third" },
        { id: "name-first", label: "Name (First)", type: "text", required: true, span: "third" },
        { id: "name-middle", label: "Name (Middle)", type: "text", span: "third" },
        { id: "birth-date", label: "Birth date", type: "date", required: true, span: "half" },
        { id: "address-street", label: "Address (Street)", type: "text", required: true, span: "half" },
        { id: "address-apt", label: "Apt #", type: "text", span: "third" },
        { id: "address-city", label: "City", type: "text", required: true, span: "third" },
        { id: "address-state", label: "State", type: "text", required: true, span: "third" },
        { id: "address-zip", label: "ZIP", type: "text", required: true, span: "third" },
        { id: "home-phone", label: "Home telephone", type: "text", span: "half" },
        { id: "business-phone", label: "Business telephone", type: "text", span: "half" },
        { id: "ssn", label: "Social Security #", type: "text", span: "half" },
        { id: "drivers-license", label: "Driver's License #", type: "text", span: "half" },
      ],
    },
    {
      id: "work-experience",
      title: "Work Experience",
      pdfPage: 8,
      fields: [
        { id: "present-position", label: "Present position", type: "text", span: "half" },
        { id: "current-employer", label: "Currently employed by", type: "text", span: "half" },
        { id: "supervisor-name", label: "Name of supervisor", type: "text", span: "full" },
        { id: "employment-from", label: "Length of employment — From", type: "date", span: "third" },
        { id: "employment-to", label: "Length of employment — To", type: "date", span: "third" },
        { id: "employment-hours-per-week", label: "Hours per week", type: "text", span: "third" },
        { id: "present-duties", label: "Duties in my present position include", type: "textarea", span: "full" },
      ],
      table: {
        id: "previous-positions",
        columns: [
          { id: "position", label: "Position / title", width: "wide" },
          { id: "employer", label: "Employed by", width: "wide" },
          { id: "from", label: "From", width: "narrow" },
          { id: "to", label: "To", width: "narrow" },
          { id: "hours-per-week", label: "Hours per week", width: "narrow" },
        ],
        rows: 3,
      },
      description: "Previous supervised positions in CCJP related fields within the last six (6) years.",
    },
    {
      id: "education-background",
      title: "Education",
      description: "See the Education Log below for listing of training. Fill out completely and attach documentation (certificates of attendance, transcripts, etc.) in the Documents section of your portal.",
      pdfPage: 9,
      fields: [
        { id: "education-high-school", label: "High School", type: "text", span: "full" },
        { id: "education-ged", label: "GED", type: "text", span: "full" },
        { id: "education-college", label: "College / University", type: "text", span: "full" },
        { id: "education-graduate", label: "Graduate School", type: "text", span: "full" },
      ],
    },
    {
      id: "education-log",
      title: "Education Log",
      description: "List the training/education applied toward the 270 contact-hour education requirement. Attach documentation for every entry in the Documents section of your portal.",
      pdfPage: 10,
      table: {
        id: "education-log-table",
        columns: [
          { id: "course-title", label: "Title of course", width: "wide" },
          { id: "hours", label: "# of hours", width: "narrow" },
          { id: "provider", label: "Facility / Provider", width: "wide" },
        ],
        rows: 12,
      },
    },
    {
      id: "practical-training-overview",
      title: "CCJP Supervised Practical Training — Overview",
      pdfPage: 11,
      notes: [
        "The supervised practical training requirement is 200 hours of clinical supervision received. All supervised training must be documented, with a minimum of 10 hours of supervision in each CCJP performance domain.",
        "Supervision is defined as the administrative, clinical, and evaluation process of monitoring, assessing and enhancing the criminal justice professional's performance.",
        "The training must take place in a setting where direct services are provided to individuals involved in the criminal justice system (law enforcement, judicial, corrections, probation/parole, etc.) and must occur as part of an eligible work experience. Supervision may be completed under more than one supervisor.",
        "The IC&RC/AODA, Inc. CCJP performance domains are: 1. Dynamics of Addiction and Criminal Behavior; 2. Legal, Ethical, and Professional Responsibility; 3. Criminal Justice Systems and Processes; 4. Screening, Intake and Assessment; 5. Case Management, Monitoring and Client Supervision; 6. Counseling.",
      ],
    },
    {
      id: "practical-training",
      title: "CCJP Supervised Practical Training",
      description: "Write below the total number of hours of supervised practical experience for each of the ICCJP performance domains. A total of 200 hours must be documented with a minimum of 10 hours in each domain.",
      pdfPage: 12,
      fields: [
        { id: "pt-applicant-name", label: "Applicant", type: "text", required: true, span: "half" },
        { id: "pt-program-name", label: "Program name", type: "text", span: "half" },
        { id: "pt-address", label: "Address (Street, City, State, Zip)", type: "text", span: "full" },
        { id: "pt-date-hired", label: "Date hired", type: "date", span: "half" },
        { id: "pt-hours-dynamics", label: "Dynamics of Addiction and Criminal Behavior — number of hours", type: "text", span: "half" },
        { id: "pt-hours-legal-ethical", label: "Legal, Ethical and Professional Responsibility — number of hours", type: "text", span: "half" },
        { id: "pt-hours-cj-systems", label: "Criminal Justice System and Process — number of hours", type: "text", span: "half" },
        { id: "pt-hours-screening", label: "Screening, Intake and Assessment — number of hours", type: "text", span: "half" },
        { id: "pt-hours-case-management", label: "Case Management, Monitoring and Client Supervision — number of hours", type: "text", span: "half" },
        { id: "pt-hours-counseling", label: "Counseling — number of hours", type: "text", span: "half" },
        { id: "pt-total-hours", label: "Total hours", type: "text", span: "half" },
      ],
    },
    {
      id: "practicum-log-1",
      title: "Supervised Field Work Practicum Log (Core Functions 1-4)",
      description: "Field work represents supervised clinical work in the criminal justice system. Log the number of hours completed in each of the six (6) Core Function areas with the dates completed. Supervisor's directions: by attesting and signing your name to the Core Function work done, you are verifying that the ten (10) required experiential hours in the specific Core Function indicated have been completed. It is your responsibility to verify by log or calendar or other mechanism that the function was indeed adequately and successfully completed.",
      pdfPage: 13,
      signerSection: { role: "Practicum Supervisor" },
      fields: [
        { id: "log-applicant-name", label: "Supervised Field Work Practicum Log for (applicant's name)", type: "text", span: "full" },
        { id: "log-dynamics-from", label: "Core Function of Dynamics of Addiction and Criminal Behavior — From (date)", type: "date", span: "half" },
        { id: "log-dynamics-hours", label: "Hours completed in the Dynamics of Addiction and Criminal Behavior", type: "text", span: "half" },
        { id: "log-dynamics-signature", label: "Supervisor's signature", type: "signature", span: "half" },
        { id: "log-dynamics-date", label: "Date", type: "date", span: "half" },
        { id: "log-legal-from", label: "Core Function of Legal, Ethical, and Professional Responsibility — From (date)", type: "date", span: "half" },
        { id: "log-legal-hours", label: "Hours completed in the Legal, Ethical, and Professional Responsibility", type: "text", span: "half" },
        { id: "log-legal-signature", label: "Supervisor's signature", type: "signature", span: "half" },
        { id: "log-legal-date", label: "Date", type: "date", span: "half" },
        { id: "log-systems-from", label: "Core Function of Criminal Justice System and Processes — From (date)", type: "date", span: "half" },
        { id: "log-systems-hours", label: "Hours completed in the Criminal Justice System and Processes", type: "text", span: "half" },
        { id: "log-systems-signature", label: "Supervisor's signature", type: "signature", span: "half" },
        { id: "log-systems-date", label: "Date", type: "date", span: "half" },
        { id: "log-screening-from", label: "Core Function of Screening, Intake, and Assessment — From (date)", type: "date", span: "half" },
        { id: "log-screening-hours", label: "Hours completed in Screening, Intake, and Assessment", type: "text", span: "half" },
        { id: "log-screening-signature", label: "Supervisor's signature", type: "signature", span: "half" },
        { id: "log-screening-date", label: "Date", type: "date", span: "half" },
      ],
    },
    {
      id: "practicum-log-2",
      title: "Supervised Field Work Practicum Log (Core Functions 5-6) and Supervisor Attestation",
      description: "The supervisor may mail this verification directly to ABCAC (PO Box 83165, Phoenix, AZ 85071, 602-402-7197).",
      pdfPage: 14,
      signerSection: { role: "Practicum Supervisor" },
      fields: [
        { id: "log-casemgmt-from", label: "Core Function of Case Management, Monitoring and Client Supervision — From (date)", type: "date", span: "half" },
        { id: "log-casemgmt-hours", label: "Hours completed in Case Management, Monitoring and Client Supervision", type: "text", span: "half" },
        { id: "log-casemgmt-signature", label: "Supervisor's signature", type: "signature", span: "half" },
        { id: "log-casemgmt-date", label: "Date", type: "date", span: "half" },
        { id: "log-counseling-from", label: "Core Function of Counseling — From (date)", type: "date", span: "half" },
        { id: "log-counseling-hours", label: "Hours completed in Counseling", type: "text", span: "half" },
        { id: "log-counseling-signature", label: "Supervisor's signature", type: "signature", span: "half" },
        { id: "log-counseling-date", label: "Date", type: "date", span: "half" },
        { id: "log-supervisor-name", label: "Information about Supervisor — Printed name", type: "text", span: "half" },
        { id: "log-supervisor-title", label: "Titled position", type: "text", span: "half" },
        { id: "log-supervisor-agency", label: "Agency or facility", type: "text", span: "half" },
        { id: "log-supervisor-phone", label: "Phone number", type: "text", span: "half" },
        { id: "log-supervisor-info-date", label: "Date", type: "date", span: "half" },
        { id: "log-attest-signature", label: "Signature of Supervisor or Program Director", type: "signature", span: "half", hint: "By signing, I attest that the applicant received supervised experience as listed above." },
        { id: "log-attest-date", label: "Date", type: "date", span: "half" },
        { id: "log-attest-print-name", label: "Print name", type: "text", span: "half" },
      ],
    },
    {
      id: "recommendation-1",
      title: "Outside Agency Letter of Recommendation",
      description: "To the Arizona Board for Certification of Addiction Counselors. This letter should attest to the applicant's character and competence and be sent directly to ABCAC by the signer — use “Invite signer” to send this section to your recommender.",
      pdfPage: 15,
      signerSection: { role: "Recommender" },
      fields: [
        { id: "rec1-applicant-name", label: "This is to certify that I have known (applicant name)", type: "text", span: "half" },
        { id: "rec1-years-known", label: "For (number of years)", type: "text", span: "half" },
        { id: "rec1-practice-location", label: "While applicant was engaged in active practice of Addiction Counseling at", type: "text", span: "full" },
        { id: "rec1-reasons", label: "I would therefore recommend the applicant to be considered for an Addiction Counseling Certificate for the following reasons", type: "textarea", span: "full" },
        { id: "rec1-name", label: "Name", type: "text", span: "half" },
        { id: "rec1-position", label: "Position", type: "text", span: "half" },
        { id: "rec1-agency", label: "Agency", type: "text", span: "half" },
        { id: "rec1-phone", label: "Area code / phone number", type: "text", span: "half" },
        { id: "rec1-address", label: "Address", type: "text", span: "full" },
        { id: "rec1-signature", label: "Signature", type: "signature", span: "half" },
        { id: "rec1-date", label: "Date", type: "date", span: "half" },
        { id: "rec1-printed-name", label: "Printed name", type: "text", span: "half" },
      ],
    },
    {
      id: "recommendation-2",
      title: "Letter of Recommendation (2)",
      description: "To the Arizona Board for Certification of Addiction Counselors. This letter should attest to the applicant's character and competence and be sent directly to ABCAC by the signer — use “Invite signer” to send this section to your recommender.",
      pdfPage: 16,
      signerSection: { role: "Recommender" },
      fields: [
        { id: "rec2-applicant-name", label: "This is to certify that I have known (applicant name)", type: "text", span: "half" },
        { id: "rec2-years-known", label: "For (number of years)", type: "text", span: "half" },
        { id: "rec2-practice-location", label: "While applicant was engaged in active practice of Addiction Counseling at", type: "text", span: "full" },
        { id: "rec2-reasons", label: "I would therefore recommend the applicant to be considered for an Addiction Counseling Certificate for the following reasons", type: "textarea", span: "full" },
        { id: "rec2-name", label: "Name", type: "text", span: "half" },
        { id: "rec2-position", label: "Position", type: "text", span: "half" },
        { id: "rec2-agency", label: "Agency", type: "text", span: "half" },
        { id: "rec2-phone", label: "Area code / phone number", type: "text", span: "half" },
        { id: "rec2-address", label: "Address", type: "text", span: "full" },
        { id: "rec2-signature", label: "Signature", type: "signature", span: "half" },
        { id: "rec2-date", label: "Date", type: "date", span: "half" },
        { id: "rec2-printed-name", label: "Printed name", type: "text", span: "half" },
      ],
    },
    {
      id: "recommendation-3",
      title: "Letter of Recommendation (3)",
      description: "To the Arizona Board for Certification of Addiction Counselors. This letter should attest to the applicant's character and competence and be sent directly to ABCAC by the signer — use “Invite signer” to send this section to your recommender.",
      pdfPage: 17,
      signerSection: { role: "Recommender" },
      fields: [
        { id: "rec3-applicant-name", label: "This is to certify that I have known (applicant name)", type: "text", span: "half" },
        { id: "rec3-years-known", label: "For (number of years)", type: "text", span: "half" },
        { id: "rec3-practice-location", label: "While applicant was engaged in active practice of Addiction Counseling at", type: "text", span: "full" },
        { id: "rec3-reasons", label: "I would therefore recommend the applicant to be considered for an Addiction Counseling Certificate for the following reasons", type: "textarea", span: "full" },
        { id: "rec3-name", label: "Name", type: "text", span: "half" },
        { id: "rec3-position", label: "Position", type: "text", span: "half" },
        { id: "rec3-agency", label: "Agency", type: "text", span: "half" },
        { id: "rec3-phone", label: "Area code / phone number", type: "text", span: "half" },
        { id: "rec3-address", label: "Address", type: "text", span: "full" },
        { id: "rec3-signature", label: "Signature", type: "signature", span: "half" },
        { id: "rec3-date", label: "Date", type: "date", span: "half" },
        { id: "rec3-printed-name", label: "Printed name", type: "text", span: "half" },
      ],
    },
    {
      id: "background",
      title: "Background Information",
      pdfPage: 18,
      fields: [
        { id: "background-held-other-state", label: "Do you hold, or have you ever held licensure, certification, or registration in any other state?", type: "yesno", required: true, hint: "If yes, complete the credential table below." },
        { id: "background-association-cert", label: "Do you hold a certification through a behavioral health professional association?", type: "yesno", required: true, detailLabel: "If yes, give professional credential held" },
        { id: "background-denied", label: "Have you ever applied for and been denied a license, certificate or registration in any behavioral health profession?", type: "yesno", required: true },
        { id: "background-disciplined", label: "Have you ever had any disciplinary action taken against you by the authority issuing the license, certificate or registration in any behavioral health profession?", type: "yesno", required: true },
        { id: "background-surrendered", label: "Have you ever surrendered or canceled your license, certificate or registration in lieu of disciplinary proceedings by the issuing authority in any behavioral health profession?", type: "yesno", required: true },
        { id: "background-association-discipline", label: "Have you ever been the subject of a disciplinary action by a regulatory committee of a professional association?", type: "yesno", required: true },
        { id: "background-convicted", label: "Have you ever been convicted or pled guilty or pled no contest to a criminal offense?", type: "yesno", required: true },
        { id: "background-malpractice", label: "Have you ever been the defendant in a malpractice suit, and either entered into a settlement agreement or paid court-awarded damages, or is there such a suit pending?", type: "yesno", required: true },
        { id: "background-terminated", label: "Have you ever been involuntarily terminated from any behavioral health or related employment for unprofessional conduct?", type: "yesno", required: true },
        { id: "background-explanation", label: "If the answers to any of these questions are YES, please explain", type: "textarea", span: "full", hint: "Enclose any relevant documents in the Documents section of your portal." },
        { id: "background-name", label: "Name", type: "text", required: true, span: "half" },
        { id: "background-date", label: "Date", type: "date", required: true, span: "half" },
      ],
      table: {
        id: "background-credentials",
        columns: [
          { id: "credential-title", label: "Title of credential", width: "wide" },
          { id: "state", label: "State", width: "narrow" },
          { id: "date-issued", label: "Date issued", width: "narrow" },
          { id: "status", label: "Current status", width: "narrow" },
        ],
        rows: 2,
      },
    },
    {
      id: "residency-authorization",
      title: "Residency Certification and Authorization",
      pdfPage: 19,
      notes: [
        "I hereby give ABCAC permission to contact the persons and institutions whom I have listed and who have provided references. I understand this application does not guarantee certification.",
        "I further agree to hold ABCAC and its credentialing committees, Board officers, Board members, agents, staff and examiners free from any civil liability or damages by reason of any action that is within their scope or arises from the performance of their duties in deciding this certification or any other activity as provided by law or regulation.",
        "If I am awarded the CCJP certification and I violate the CCJP Code of Ethics or have a sanction lodged against me, I am aware that ABCAC may publish or release my name to a National Data Bank and to the Arizona State of Behavioral Health.",
      ],
      fields: [
        { id: "residency-signature", label: "Residency certification signature", type: "signature", required: true, span: "full", hint: "This is to certify that I have been a resident of the State of Arizona for a period of at least one year immediately prior to submitting application." },
        { id: "authorization-signature", label: "Signature", type: "signature", required: true, span: "half" },
        { id: "authorization-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "authorization-print-name", label: "Print name", type: "text", required: true, span: "full" },
      ],
    },
    {
      id: "code-of-ethics",
      title: "CCJP Code of Ethical Conduct",
      description: "Read the full Certified Criminal Justice Professional (CCJP) Code of Ethical Conduct before signing the agreement below. The twelve principles are summarized here; the complete text appears in the original application packet.",
      pdfPage: 20,
      notes: [
        "Principle 1 — Non-Discrimination: the CCJP shall not discriminate against clients or professionals based on race, religion, age, gender, disability, national ancestry, sexual orientation or economic condition.",
        "Principle 2 — Responsibility: the CCJP shall espouse objectivity and integrity, and maintain the highest standards in the services offered, including reporting unethical conduct to the appropriate authority.",
        "Principle 3 — Competence: the CCJP shall recognize the boundaries and limitations of the CCJP's competencies, not offer services outside them, and pursue ongoing education as a component of professional competency.",
        "Principle 4 — Legal and Moral Standards: the CCJP shall uphold the legal and accepted moral codes pertaining to professional conduct and shall not claim professional qualifications or affiliations the CCJP does not possess.",
        "Principle 5 — Public Statements: the CCJP shall honestly respect the limits of present knowledge in public statements concerning alcoholism and drug abuse, representing unvalidated opinions as such.",
        "Principle 6 — Publication Credit: the CCJP shall assign credit to all who have contributed to published material and shall not violate copyright.",
        "Principle 7 — Client Welfare: the CCJP shall promote the protection of the public health, safety and welfare and the best interest of the client as a primary guide, including privacy and safety of service delivery.",
        "Principle 8 — Confidentiality: the CCJP shall protect the client's rights under confidentiality and not disclose confidential information without appropriately executed consent, adhering to all federal and state laws.",
        "Principle 9 — Client Relationships: the CCJP shall safeguard the integrity of the counseling relationship, avoid dual relationships and exploitation, and shall not under any circumstances engage in sexual behavior with current or former clients.",
        "Principle 10 — Inter-professional Relationships: the CCJP shall treat colleagues with respect, courtesy, fairness and good faith, cooperate with professional ethics committees, and not exploit supervisory or similar relationships.",
        "Principle 11 — Remuneration: the CCJP shall establish financial arrangements that safeguard the best interests of the client first, inform clients of all financial policies, and not engage in fee splitting.",
        "Principle 12 — Societal Obligations: the CCJP shall actively engage public policy and legislative processes, educational institutions, and the general public to expand opportunities and choice of service for all whose lives are impaired by alcoholism and drug abuse.",
      ],
    },
    {
      id: "ethics-agreement",
      title: "ABCAC Code of Ethical Conduct Agreement",
      description: "Each applicant for the CCJP certification must read, sign and adhere to the Code of CCJP Ethical Conduct. Penalty for violation of the CCJP ethical conduct and standards may result in suspension, sanctions or revocation of certification.",
      pdfPage: 25,
      fields: [
        { id: "ethics-signature", label: "Applicant signature", type: "signature", required: true, span: "half", hint: "I, the undersigned individual, agree to adhere to the Code of Ethical Standards and understand that violation of the ethical standards may result in sanctions including loss of the CCJP credential." },
        { id: "ethics-date", label: "Date", type: "date", required: true, span: "half" },
        { id: "ethics-print-name", label: "Print name", type: "text", required: true, span: "full" },
      ],
    },
  ],
};
