import type { NativeFormSchema } from "@/lib/native-schemas/types";

// Native (HTML) version of the ABCAC Certified Clinical Supervisor (CCS)
// application manual. Section pdfPage numbers reference the original PDF.

export const INITIAL_CCS_SCHEMA: NativeFormSchema = {
  formKey: "initial-ccs",
  intro: {
    title: "Application for Certified Clinical Supervisor (CCS)",
    paragraphs: [
      "The Clinical Supervisor credential upgrades and standardizes the qualifications of individuals working in the supervision of addictions counselors. ICRC defines Clinical Supervision as a specific aspect of staff development dealing with clinical skills and competencies for persons providing counseling; a primary purpose is to enhance skill development as evidenced by provision of quality patient care. Supervision is typically one-to-one or in small groups held on a regular basis, using intensive case review and discussion and direct and indirect observation of clinical practice.",
      "Health professionals with the Clinical Supervisor credential are certified by ABCAC as having been adequately trained to provide supervision for counselor interns and counselors. The services of a CCS shall be within the limitations of all applicable state and local statutes; where statute requires that a CCS be supervised by a licensed provider, they shall so be supervised.",
      "The CCS performance domains are: Assessment and Evaluation (assessing the supervisee's knowledge, experience, clinical functioning, leadership style, and performance of tasks related to the ADC Domains); Counselor Development (building clinical skills and promoting career and educational growth through assessment activities, case presentation, demonstration, and dialogue); Professional Responsibility (modeling professional involvement, adhering to an established code of ethics, respecting supervisee uniqueness, improving supervisory competence, and abiding by federal, state, local, and agency rules); and Management and Administration (monitoring regulatory compliance, evaluating agency policies, quality improvement, orienting new staff, staff selection and review, and program development).",
    ],
  },
  sections: [
    {
      id: "requirements",
      title: "Requirements for Clinical Supervisor Certification",
      description: "Review these requirements before completing the application. No entries are needed in this section.",
      pdfPage: 4,
      notes: [
        "Prerequisite: current credentialing as an AODA counselor at the reciprocal level ADC, AADC, CCJP, or hold a specialty substance abuse credential in another professional discipline in human services at a Master's level or higher.",
        "Experience: verification of five (5) years (10,000 hours) of counseling experience as an alcohol and drug abuse counselor. An Associate's degree can exchange for 1,000 hours; a BA/BS in a Behavioral Science can exchange for 2,000 hours; a Master's degree in a Behavioral Science can exchange for 4,000 hours.",
        "Experience: verification of two (2) years (4,000 hours) of clinical supervisory experience in the alcohol and drug abuse field. These hours may be included in the 10,000 hours of counseling experience. This must include 200 contact hours of face-to-face clinical supervision; 100 hours may be performed electronically in real time.",
        "Education: verification of thirty (30) hours of education related to clinical supervision, including education in each of the following areas: 1. Assessment/Evaluation, 2. Counselor Development, 3. Management/Administration, and 4. Professional Responsibilities.",
        "Examination: pass the IC&RC Clinical Supervisor examination.",
        "Code of Ethics: signed Code of Ethics / Affirmation Statement verifying that you read, understood, and will adhere to ABCAC's code of ethics as a Clinical Supervisor. There is a written enforcement and appeals process if a professional violates the board's code of ethics.",
        "Recertification: at least 6 hours of continuing education in Clinical Supervision, 3 hours of Ethics, and 3 hours of Cultural Diversity every 2 years (may be part of the 40 hours obtained for the prerequisite credential). Recertification requires current certification as a CADAC, a completed recertification application with documentation and $150.00 fee, a signed copy of the ethical standards for clinical supervisors, and absence of any ethical violation or malpractice judgements during the two year period.",
        "Residency: must live or work 51% of the time in Arizona. This applies only at the time of initial application for the credential.",
      ],
    },
    {
      id: "checklist",
      title: "CCS Application Checklist",
      description: "Everything your application must include. No entries are needed in this section.",
      pdfPage: 6,
      notes: [
        "1. Application for Certified Clinical Supervisor.",
        "2. Qualifying Work Experience form.",
        "3. Educational Record form and appropriate documentation (upload certificates and transcripts in the Documents section of your portal).",
        "4. Signed Code of Ethics for Certified Clinical Supervisors.",
        "5. Signed Statement of Understanding.",
        "6. The $375.00 application fee (check or money order made out to ABCAC, or pay online at checkout). This covers the application manual, exam fee, processing fees, and 2 years of certification.",
        "Three (3) copies of the Supervisor Evaluation/Reference form must be sent directly from your selected individuals to the ABCAC office; one must be completed by your clinical supervisor. Use the evaluation sections below to invite each reference as a signer.",
      ],
    },
    {
      id: "applicant",
      title: "Applicant Information",
      description: "Please print or type.",
      pdfPage: 7,
      fields: [
        { id: "name-last", label: "Last name", type: "text", required: true, span: "third" },
        { id: "name-first", label: "First name", type: "text", required: true, span: "third" },
        { id: "name-mi", label: "Middle initial", type: "text", span: "third" },
        { id: "home-street", label: "Home address (number and street)", type: "text", required: true, span: "half" },
        { id: "home-apt", label: "Apt/Unit #", type: "text", span: "half" },
        { id: "home-city", label: "City", type: "text", required: true, span: "third" },
        { id: "home-state", label: "State", type: "text", required: true, span: "third" },
        { id: "home-zip", label: "ZIP code", type: "text", required: true, span: "third" },
        { id: "home-phone", label: "Home phone", type: "text", span: "half" },
        { id: "work-phone", label: "Work phone", type: "text", span: "half" },
        { id: "email", label: "Email", type: "text", required: true, span: "half" },
        { id: "date-of-birth", label: "Date of birth", type: "date", required: true, span: "half" },
        { id: "certificate-name", label: "Name as you would like it to appear on your certificate", type: "text", required: true, span: "full" },
      ],
    },
    {
      id: "current-position",
      title: "Current Position",
      pdfPage: 7,
      fields: [
        { id: "job-title", label: "Job title", type: "text", span: "half" },
        { id: "agency-employer", label: "Agency/Employer", type: "text", span: "half" },
        { id: "employer-address", label: "Employer address", type: "text", span: "full" },
        { id: "employed-from", label: "Date employed — from", type: "date", span: "third" },
        { id: "employed-to", label: "Date employed — to", type: "date", span: "third" },
        { id: "employed-hours-week", label: "Hours/week", type: "text", span: "third" },
        { id: "position-supervisor-name", label: "Supervisor name", type: "text", span: "half" },
        { id: "position-supervisor-phone", label: "Supervisor phone", type: "text", span: "half" },
        { id: "supervision-hours-week", label: "Hours/week applicant spends providing clinical supervision", type: "text", span: "full", hint: "Applicant must be able to document 200 hours of direct clinical supervision provided to counselors within the past 2 years." },
      ],
    },
    {
      id: "supervisor-verification",
      title: "Supervisor Verification of Clinical Supervision Time",
      description: "To be completed by the applicant's clinical supervisor. I hereby attest that the applicant is working in a position in which a minimum of 26% of his/her time (OR a minimum of 200 hours in the past 2 years) is spent providing clinical supervision to alcohol and other drug abuse counselors and/or interns. Use “Invite signer” below to send this section to your supervisor.",
      pdfPage: 7,
      signerSection: { role: "Clinical Supervisor" },
      fields: [
        { id: "verify-supervisor-signature", label: "Supervisor's signature", type: "signature", span: "half" },
        { id: "verify-supervisor-date", label: "Date", type: "date", span: "half" },
      ],
    },
    {
      id: "work-experience",
      title: "Qualifying Work Experience",
      description: "Please list your current position first (row 1). The original form provides five identical employment blocks; complete one row per employer.",
      pdfPage: 8,
      notes: [
        "Attach a copy of your job description (current position only) signed by your immediate supervisor in the Documents section of your portal.",
        "Include your supervisory functions in the job duties column.",
      ],
      table: {
        id: "work-experience-log",
        columns: [
          { id: "employer", label: "Name of employer", width: "wide" },
          { id: "address", label: "Address", width: "wide" },
          { id: "supervisor", label: "Immediate supervisor", width: "wide" },
          { id: "phone", label: "Agency phone number", width: "narrow" },
          { id: "from", label: "Dates employed — from", width: "narrow" },
          { id: "to", label: "Dates employed — to", width: "narrow" },
          { id: "hours-week", label: "Hours per week", width: "narrow" },
          { id: "duties", label: "Job duties (including supervisory functions)", width: "wide" },
        ],
        rows: 5,
      },
    },
    {
      id: "formal-education",
      title: "Educational Record — Formal Education",
      description: "List all formal education you have received.",
      pdfPage: 13,
      table: {
        id: "formal-education-log",
        columns: [
          { id: "school", label: "School", width: "narrow" },
          { id: "location", label: "Location", width: "wide" },
          { id: "dates-attended", label: "Dates attended", width: "narrow" },
          { id: "date-graduated", label: "Date graduated", width: "narrow" },
          { id: "degree", label: "Degree", width: "narrow" },
        ],
        rows: 3,
        fixedFirstColumn: ["High School", "College", "Graduate School"],
      },
    },
    {
      id: "supervision-training",
      title: "Educational Record — Clinical Supervision Training",
      description: "List training events specific to clinical supervision. A minimum of 30 (thirty) hours of education/training in clinical supervision is required. For each course, note which content areas were covered: Assessment/Evaluation, Counselor Development, Management/Administration, and/or Professional Responsibility (check 1 or more).",
      pdfPage: 13,
      notes: [
        "Document any additional training hours beyond these five entries on separate paper and attach it in the Documents section of your portal.",
        "Be sure to attach documentation (i.e., certificates, transcripts) which supports participation in the Documents section of your portal. Lack of appropriate documentation will result in loss of those educational hours.",
      ],
      table: {
        id: "supervision-training-log",
        columns: [
          { id: "title", label: "Course / program title", width: "wide" },
          { id: "dates", label: "Dates attended", width: "narrow" },
          { id: "clock-hours", label: "Clock hours", width: "narrow" },
          { id: "sponsor", label: "Sponsoring organization", width: "wide" },
          { id: "content", label: "Content covered (list 1 or more of the four areas)", width: "wide" },
        ],
        rows: 5,
      },
    },
    {
      id: "evaluation-1",
      title: "Supervisor Evaluation / Reference Form — Reference 1 (Clinical Supervisor)",
      description: "Three copies of this form need to be completed by individuals familiar with your work as a clinical supervisor and submitted directly by each of them to ABCAC. One of your references must be your clinical supervisor (who must also verify by signature on your application that you have completed 200 hours of direct clinical supervision in the past two years). Use “Invite signer” below to send this section to your reference.",
      pdfPage: 15,
      signerSection: { role: "Reference (Clinical Supervisor)" },
      notes: [
        "Instructions to the reference: using the six point (0-5) scale below, enter the number which most nearly describes the applicant's ability in each category in the Score column. If you have no basis for evaluating the applicant in a particular area, enter 0. Please comment briefly on the basis for each given score.",
        "Rating scale: 0 = No basis for judgement, 1 = Inadequate, 2 = Needs development, 3 = Acceptable, 4 = Good, 5 = Outstanding.",
      ],
      fields: [
        { id: "eval1-applicant-name", label: "Applicant's name", type: "text", span: "half" },
        { id: "eval1-referee-name-title", label: "Supervisor's name and title", type: "text", span: "half" },
        { id: "eval1-work-address", label: "Work address", type: "text", span: "half" },
        { id: "eval1-work-phone", label: "Work phone number", type: "text", span: "half" },
        { id: "eval1-known-how-long", label: "How long have you known the applicant?", type: "text", span: "half" },
        { id: "eval1-relation-supervisor", label: "Relation to applicant: Supervisor", type: "check", span: "third" },
        { id: "eval1-relation-colleague", label: "Relation to applicant: Colleague", type: "check", span: "third" },
        { id: "eval1-relation-other", label: "Relation to applicant: Other (specify)", type: "text", span: "third" },
        { id: "eval1-total-score", label: "Total score", type: "text", span: "third" },
        { id: "eval1-signature", label: "Supervisor signature", type: "signature", span: "half" },
        { id: "eval1-date", label: "Date", type: "date", span: "half" },
      ],
      table: {
        id: "eval1-scores",
        columns: [
          { id: "item", label: "Knowledge / skill area", width: "wide" },
          { id: "score", label: "Score", width: "narrow" },
          { id: "comments", label: "Comments", width: "wide" },
        ],
        rows: 6,
        fixedFirstColumn: [
          "1. An advanced knowledge on how substance abuse relates to other physical, behavioral, cognitive, emotional, socio-cultural, and economic aspects of mental and emotional disorders and adjustment reactions.",
          "2. A demonstrated familiarity with a variety of therapeutic modalities.",
          "3. An operational experience with a variety of treatment approaches used in the field of substance abuse.",
          "4. Ability to deal effectively with supervisee's psychodynamics as they relate to his/her work with clients.",
          "5. Knowledge of various roles and techniques employed in the clinical supervision process.",
          "6. How well does applicant use existing supervision?",
        ],
      },
    },
    {
      id: "evaluation-2",
      title: "Supervisor Evaluation / Reference Form — Reference 2",
      description: "Second of three evaluation/reference forms, completed by an individual familiar with your work as a clinical supervisor and submitted directly to ABCAC. Use “Invite signer” below to send this section to your reference.",
      pdfPage: 17,
      signerSection: { role: "Reference" },
      notes: [
        "Instructions to the reference: using the six point (0-5) scale below, enter the number which most nearly describes the applicant's ability in each category in the Score column. If you have no basis for evaluating the applicant in a particular area, enter 0. Please comment briefly on the basis for each given score.",
        "Rating scale: 0 = No basis for judgement, 1 = Inadequate, 2 = Needs development, 3 = Acceptable, 4 = Good, 5 = Outstanding.",
      ],
      fields: [
        { id: "eval2-applicant-name", label: "Applicant's name", type: "text", span: "half" },
        { id: "eval2-referee-name-title", label: "Supervisor's name and title", type: "text", span: "half" },
        { id: "eval2-work-address", label: "Work address", type: "text", span: "half" },
        { id: "eval2-work-phone", label: "Work phone number", type: "text", span: "half" },
        { id: "eval2-known-how-long", label: "How long have you known the applicant?", type: "text", span: "half" },
        { id: "eval2-relation-supervisor", label: "Relation to applicant: Supervisor", type: "check", span: "third" },
        { id: "eval2-relation-colleague", label: "Relation to applicant: Colleague", type: "check", span: "third" },
        { id: "eval2-relation-other", label: "Relation to applicant: Other (specify)", type: "text", span: "third" },
        { id: "eval2-total-score", label: "Total score", type: "text", span: "third" },
        { id: "eval2-signature", label: "Supervisor signature", type: "signature", span: "half" },
        { id: "eval2-date", label: "Date", type: "date", span: "half" },
      ],
      table: {
        id: "eval2-scores",
        columns: [
          { id: "item", label: "Knowledge / skill area", width: "wide" },
          { id: "score", label: "Score", width: "narrow" },
          { id: "comments", label: "Comments", width: "wide" },
        ],
        rows: 6,
        fixedFirstColumn: [
          "1. An advanced knowledge on how substance abuse relates to other physical, behavioral, cognitive, emotional, socio-cultural, and economic aspects of mental and emotional disorders and adjustment reactions.",
          "2. A demonstrated familiarity with a variety of therapeutic modalities.",
          "3. An operational experience with a variety of treatment approaches used in the field of substance abuse.",
          "4. Ability to deal effectively with supervisee's psychodynamics as they relate to his/her work with clients.",
          "5. Knowledge of various roles and techniques employed in the clinical supervision process.",
          "6. How well does applicant use existing supervision?",
        ],
      },
    },
    {
      id: "evaluation-3",
      title: "Supervisor Evaluation / Reference Form — Reference 3",
      description: "Third of three evaluation/reference forms, completed by an individual familiar with your work as a clinical supervisor and submitted directly to ABCAC. Use “Invite signer” below to send this section to your reference.",
      pdfPage: 19,
      signerSection: { role: "Reference" },
      notes: [
        "Instructions to the reference: using the six point (0-5) scale below, enter the number which most nearly describes the applicant's ability in each category in the Score column. If you have no basis for evaluating the applicant in a particular area, enter 0. Please comment briefly on the basis for each given score.",
        "Rating scale: 0 = No basis for judgement, 1 = Inadequate, 2 = Needs development, 3 = Acceptable, 4 = Good, 5 = Outstanding.",
      ],
      fields: [
        { id: "eval3-applicant-name", label: "Applicant's name", type: "text", span: "half" },
        { id: "eval3-referee-name-title", label: "Supervisor's name and title", type: "text", span: "half" },
        { id: "eval3-work-address", label: "Work address", type: "text", span: "half" },
        { id: "eval3-work-phone", label: "Work phone number", type: "text", span: "half" },
        { id: "eval3-known-how-long", label: "How long have you known the applicant?", type: "text", span: "half" },
        { id: "eval3-relation-supervisor", label: "Relation to applicant: Supervisor", type: "check", span: "third" },
        { id: "eval3-relation-colleague", label: "Relation to applicant: Colleague", type: "check", span: "third" },
        { id: "eval3-relation-other", label: "Relation to applicant: Other (specify)", type: "text", span: "third" },
        { id: "eval3-total-score", label: "Total score", type: "text", span: "third" },
        { id: "eval3-signature", label: "Supervisor signature", type: "signature", span: "half" },
        { id: "eval3-date", label: "Date", type: "date", span: "half" },
      ],
      table: {
        id: "eval3-scores",
        columns: [
          { id: "item", label: "Knowledge / skill area", width: "wide" },
          { id: "score", label: "Score", width: "narrow" },
          { id: "comments", label: "Comments", width: "wide" },
        ],
        rows: 6,
        fixedFirstColumn: [
          "1. An advanced knowledge on how substance abuse relates to other physical, behavioral, cognitive, emotional, socio-cultural, and economic aspects of mental and emotional disorders and adjustment reactions.",
          "2. A demonstrated familiarity with a variety of therapeutic modalities.",
          "3. An operational experience with a variety of treatment approaches used in the field of substance abuse.",
          "4. Ability to deal effectively with supervisee's psychodynamics as they relate to his/her work with clients.",
          "5. Knowledge of various roles and techniques employed in the clinical supervision process.",
          "6. How well does applicant use existing supervision?",
        ],
      },
    },
    {
      id: "code-of-ethics",
      title: "Code of Ethics for Certified Clinical Supervisors",
      description: "Read the Code of Ethics summarized below, then sign to affirm that you have read, understood, and will adhere to it.",
      pdfPage: 21,
      notes: [
        "Non-Discrimination: the counselor must not discriminate against patients or others based on race, religion, age, sex, national ancestry, sexual orientation, economic condition, or disability.",
        "Responsibilities: exercise competent professional judgement when dealing with clients and other professionals and, at all times, maintain the best interests of patients when providing counseling.",
        "Competence: provide competent professional service in keeping with ABCAC standards, including thorough knowledge of alcohol and other drug abuse, skill in presentation and counseling techniques, thorough preparation, and a willingness to maintain current knowledge through on-going professional education.",
        "Professional Standards: do not claim knowledge, qualifications, or affiliations you do not possess; lend your name to relationships that mislead the public; misrepresent your certification or make false statements to ABCAC; compromise your professional status with a patient through commercial products; fail to recognize professional impairment (e.g., intoxication, drug use relapse) and the need to seek treatment; or enter into business relationships adverse to your patient.",
        "Professional Obligations to the Public: do not champion your own cause by denigrating others, and do not engage in false or misleading communication about your own or other professionals' abilities, training, and/or experience.",
        "Publications: acknowledge and document any materials, techniques, or people used in creating your papers, books, etc. Seek permission from the author/creator of such materials; use of copyrighted materials without author approval is against the law and in violation of professional standards.",
        "Patient Welfare: place the best interest of the patient first, provide an appropriate setting for clinical work, and provide a supportive environment for patients having special needs.",
        "Confidentiality: determine the patient's needs and expectations regarding confidentiality, advise the patient of its limits, and be aware of and in compliance with all applicable State and Federal guidelines, regulations, statutes, and agency policies regarding confidentiality.",
        "Patient Relationships: do not engage in any sexual activity with or date a patient receiving treatment from you or your agency, counsel your own family members, or counsel patients when your objectivity may be limited by a third-party relationship.",
        "Professional Integrity: never knowingly make a false statement to ABCAC or any other disciplinary authority; promptly alert colleagues informally to potentially unethical behavior; and report violations of professional conduct to the appropriate licensing/disciplinary authority when a counselor has failed to take corrective action after formal intervention.",
        "Financial Arrangements: do not accept fees or gratuities for professional work from a person who is entitled to, and reliant upon, such services through an institution and/or agency.",
        "Professional Promotion: strive to maintain and promote the integrity of certification within the State of Arizona, nationally and internationally, and the advancement of the profession.",
      ],
      fields: [
        { id: "ethics-signature", label: "Signature", type: "signature", required: true, span: "half" },
        { id: "ethics-date", label: "Date", type: "date", required: true, span: "half" },
      ],
    },
    {
      id: "statement-of-understanding",
      title: "Statement of Understanding",
      description: "I hereby request that the Arizona Board for Certification of Addictions Counselors (ABCAC) grant the CCS certificate to me based on the following assurances.",
      pdfPage: 23,
      notes: [
        "I subscribe to and commit myself to professional conduct in keeping with the Certified Clinical Supervisor Code of Ethics.",
        "I hereby affirm that this application is made on my behalf and is entirely voluntary on my part. I authorize ABCAC to request and receive all records and/or information relating to my application for certification as a clinical supervisor, including but not limited to verbal or written contacts with my employer(s), academic and training institutions, and/or other persons or organizations having pertinent information. This is a waiver of my privilege that may otherwise exist in respect to the disclosure of such information.",
        "I hereby certify that the information given herein is true and complete to the best of my knowledge and belief. I understand that intentionally false or misleading statements on this application will result in my being declared ineligible for certification. Data from my application may be used for statistical purposes.",
        "I understand that approval of my application depends upon my meeting the requirements and criteria established by ABCAC.",
      ],
      fields: [
        { id: "understanding-applicant-name", label: "Applicant name", type: "text", required: true, span: "full" },
        { id: "understanding-signature", label: "Signature", type: "signature", required: true, span: "half" },
        { id: "understanding-date", label: "Date", type: "date", required: true, span: "half" },
      ],
    },
  ],
};
