import type { NativeFormSchema } from "@/lib/native-schemas/types";

// Native schema for the Certified Prevention Specialist (CPS) application
// manual (25-page PDF). Informational pages are condensed into the intro and
// section notes; every fillable blank of the original packet is a field.

const RATING_SCALE_NOTES: string[] = [
  "Rating scale: 0 = No basis for judgement, 1 = Inadequate, 2 = Needs development, 3 = Acceptable, 4 = Good, 5 = Outstanding.",
  "Determine the number that most nearly describes the applicant's ability in each category and enter it under Score. If you have no basis for evaluating the applicant in a particular area, enter 0.",
  "If you wish to make additional comments, attach additional sheets (evaluators may upload them in the Documents section of the portal).",
];

const RATING_ATTRIBUTES: string[] = [
  "1. Knowledge of basic helping skills",
  "2. Skill in active listening, summarizing, appropriate self-disclosure",
  "3. Enthusiasm, warmth, respect, genuineness, empathy",
  "4. Personal and professional honesty",
  "5. Knowledge of prevention modalities and strategies (developing, delivering, evaluating and facilitating prevention programs; problem solving techniques; writing various formats)",
  "6. Ability to work with others, within a team setting, and with other agencies",
  "7. Professional ethical conduct and compliance with confidentiality regulations",
  "8. Knowledge of alcohol, tobacco, and other drug dependency field",
  "9. Common sense and sense of responsibility",
  "10. Ability to assess needs and document recipients and to make appropriate referrals",
  "11. Personal integrity",
  "12. Appropriateness of relationships with recipients",
  "13. Ability to maintain professional objectivity",
  "14. Communication skills, both orally and in writing",
  "15. Knowledge of and compliance with confidentiality regulations and ethics",
];

/** One employer block of the Qualifying Work Experience form (pages 10-11). */
function employmentBlockFields(prefix: string, blockLabel: string) {
  return [
    { id: `${prefix}-agency`, label: `${blockLabel} — Agency / Employer`, type: "text" as const, span: "full" as const },
    { id: `${prefix}-agency-street`, label: "Agency address (number & street)", type: "text" as const, span: "full" as const },
    { id: `${prefix}-agency-city-state-zip`, label: "City / State / ZIP code", type: "text" as const, span: "half" as const },
    { id: `${prefix}-agency-phone`, label: "Agency phone", type: "text" as const, span: "half" as const },
    { id: `${prefix}-agency-fax`, label: "Fax #", type: "text" as const, span: "half" as const },
    { id: `${prefix}-supervisor`, label: "Immediate supervisor (title, last, first, MI)", type: "text" as const, span: "half" as const },
    { id: `${prefix}-dates-from`, label: "Dates employed — from", type: "date" as const, span: "third" as const },
    { id: `${prefix}-dates-to`, label: "Dates employed — to", type: "date" as const, span: "third" as const },
    { id: `${prefix}-hours-per-week`, label: "Hours per week", type: "text" as const, span: "third" as const },
    { id: `${prefix}-job-title`, label: "Job title", type: "text" as const, span: "full" as const },
    { id: `${prefix}-duties`, label: "Duties", type: "textarea" as const, span: "full" as const },
  ];
}

/** Formal-education row of the Educational Record (page 13). */
function formalEducationFields(prefix: string, levelLabel: string) {
  return [
    { id: `${prefix}-dates-attended`, label: `${levelLabel} — Dates attended`, type: "text" as const, span: "third" as const },
    { id: `${prefix}-date-graduated`, label: "Date graduated", type: "text" as const, span: "third" as const },
    { id: `${prefix}-degree`, label: "Degree", type: "text" as const, span: "third" as const },
    { id: `${prefix}-name-location`, label: "Name / Location", type: "text" as const, span: "full" as const },
  ];
}

export const INITIAL_CPS_SCHEMA: NativeFormSchema = {
  formKey: "initial-cps",
  intro: {
    title: "Certified Prevention Specialist (CPS) Application",
    paragraphs: [
      "The Arizona Board for Certification of Addiction Counselors (ABCAC) enhances the quality of substance abuse services in Arizona by certifying substance abuse professionals. The CPS credential defines the essential role and functions of the prevention specialist in the chemical dependency continuum of care, offers guidance to employers and consumers, and provides the prevention specialist a tool for marketing unique skills and competence. ABCAC does not discriminate against applicants on the basis of sex, age, race, national origin, creed or sexual orientation.",
      "A prevention specialist is a professional who uses specialized knowledge, experience, training and skills to encourage healthy attitudes and behaviors which prevent the abuse of alcohol, tobacco, and other drugs (ATOD). The role, as defined in the Prevention Performance Domains, is to empower individuals and communities to assess needs and to develop and implement strategies that effectively meet the goals of the community.",
      "The certification process is based on specific measurable competencies across six Prevention Performance Domains: Program Coordination; Education and Training; Community Organization; Public Policy; Professional Growth and Responsibility; and Planning and Evaluation. In addition to demonstrating these knowledge and skill competencies, applicants must also meet established education and experience requirements (see the Specific Requirements section below). The full task outlines for each domain appear on pages 3-5 of the original application manual.",
    ],
  },
  sections: [
    {
      id: "specific-requirements",
      title: "Specific Requirements",
      description: "IC&RC minimum standards for the Prevention Specialist credential. Review before completing the application — no entries are required in this section.",
      pdfPage: 6,
      notes: [
        "2,000 hours of work experience specific to Prevention.",
        "Verification of 120 hours of education specific to the six performance domains: Planning and Evaluation; Prevention Education and Service Delivery; Communication; Community Organization; Public Policy and Environmental Change; Professional Growth and Responsibility. 24 of these 120 hours must be specific to Alcohol, Tobacco, and Other Drug (ATOD) use and abuse. Must have six (6) hours of prevention ethics education and four (4) hours of HIV/AIDS education.",
        "Verification of 120 hours of supervised experience in the six performance domains, with a minimum of 10 hours in each domain.",
        "Successful completion of the IC&RC Prevention Specialist examination.",
        "Read, agree, and sign ABCAC's Code of Ethics for Prevention Specialists. There is a written enforcement and appeals process if a professional violates ABCAC's Code of Ethics.",
        "Recertification requires 40 hours of prevention specialist continuing education every 2 years, or 20 hours every year of certification.",
        "Applicants must live and/or work at least 51% of the time in the jurisdiction of ABCAC at the time of application. Applicants who reside in an IC&RC member area may apply for reciprocity of work experience and education obtained through an IC&RC member agency; applicants from a non-member IC&RC area must complete all requirements within the jurisdiction of ABCAC.",
        "Sources of education are college courses, seminars, conferences, in-services, institutes, lectures, workshops, etc. One college credit is equivalent to 15 clock hours; three college credits are equivalent to 45 clock hours. All sources of education must be presented with documentation.",
        "Fees: Application Manual and Process fee $150.00 (non-refundable); Exam fee $225.00; Retest fee $225.00; Recertification fee $150.00.",
      ],
    },
    {
      id: "recertification-requirements",
      title: "Recertification Requirements (for reference)",
      description: "Recertification is an administrative review of continuing education hours and must be earned every two years. No entries are required in this section.",
      pdfPage: 7,
      notes: [
        "Maintain current and valid certification as a Certified Prevention Specialist issued by ABCAC.",
        "Document forty (40) approved hours of continuing education related to prevention obtained during the two-year certification period: a minimum of twenty (20) of the 40 hours must be related to the knowledge and skills necessary to perform the tasks within the performance domains; a maximum of twenty (20) hours of related in-service training is acceptable; three (3) hours of prevention ethics education and three (3) hours of Cultural Diversity education must be included in the 40 hours.",
        "The applicant for recertification must be free of any ethical violations or malpractice judgements during the two-year period.",
        "The recertification fee of $150.00 must accompany the completed recertification application and documentation.",
      ],
    },
    {
      id: "application-checklist",
      title: "Application Checklist",
      description: "The following must be included in the application package submitted to ABCAC.",
      pdfPage: 8,
      notes: [
        "1. Application for Certified Prevention Specialist (completed below).",
        "2. Qualifying Work Experience form (completed below).",
        "3. Supervised Prevention Experience form (completed by your immediate supervisor).",
        "4. Educational Record form and appropriate documentation — upload supporting documentation in the Documents section of your portal.",
        "5. Certificate of completion of six hours of Ethics and four hours of HIV/AIDS Education — upload in the Documents section of your portal.",
        "6. Signed Statement of Understanding form (completed below).",
        "7. $375 fee — covers the cost of the application manual, processing fees, the IC&RC Prevention exam, and 2 years of certification. On paper this is a check or money order mailed to ABCAC, P.O. Box 83165, Phoenix, Arizona 85071; no payment entry is made on this form.",
        "8-9. A Supervisor Evaluation/Recommendation and TWO Peer Evaluation/Recommendations must reach the ABCAC office directly from the selected individuals (Attn: CPS Committee). Use the Invite signer option on those sections to send them securely.",
      ],
    },
    {
      id: "application",
      title: "Application",
      description: "Please type or print all information.",
      pdfPage: 9,
      notes: [
        "ABCAC reserves the right to request further information from employers and other persons or agencies listed on this application. The ABCAC Committee on Prevention Certification reserves the option to personally interview the applicant.",
      ],
      fields: [
        { id: "application-date", label: "Date", type: "date", required: true, span: "third" },
        { id: "name-last", label: "Name — Last", type: "text", required: true, span: "third" },
        { id: "name-first", label: "First", type: "text", required: true, span: "third" },
        { id: "name-mi", label: "Middle initial", type: "text", span: "third" },
        { id: "home-street", label: "Home address (number & street, apt/suite/unit)", type: "text", required: true, span: "full" },
        { id: "home-city", label: "City", type: "text", required: true, span: "third" },
        { id: "home-state", label: "State", type: "text", required: true, span: "third" },
        { id: "home-zip", label: "ZIP code", type: "text", required: true, span: "third" },
        { id: "home-phone", label: "Home phone", type: "text", span: "third" },
        { id: "work-phone", label: "Work phone", type: "text", span: "third" },
        { id: "fax", label: "Fax #", type: "text", span: "third" },
        { id: "ssn", label: "Social Security no.", type: "text", span: "half" },
        { id: "date-of-birth", label: "Date of birth (MM/DD/YYYY)", type: "date", required: true, span: "half" },
        { id: "job-title", label: "Job title", type: "text", span: "half" },
        { id: "agency-employer", label: "Agency / Employer", type: "text", span: "half" },
        { id: "agency-street", label: "Agency address (number & street)", type: "text", span: "full" },
        { id: "agency-city-state-zip", label: "City / State / ZIP code", type: "text", span: "full" },
        { id: "employed-from", label: "Dates employed — from (MM/DD/YYYY)", type: "date", span: "third" },
        { id: "employed-to", label: "To (MM/DD/YYYY)", type: "date", span: "third" },
        { id: "employed-hours-week", label: "Hours / week", type: "text", span: "third" },
        { id: "current-supervisor", label: "Supervisor", type: "text", span: "half" },
        { id: "current-supervisor-phone", label: "Supervisor phone", type: "text", span: "half" },
        { id: "certificate-name", label: "Please print your name exactly as you wish it to appear on your certificate", type: "text", required: true, span: "full" },
      ],
      table: {
        id: "licenses",
        columns: [
          { id: "credential", label: "License / Certification & Number", width: "wide" },
          { id: "date", label: "Date", width: "narrow" },
          { id: "state", label: "State", width: "narrow" },
        ],
        rows: 3,
      },
    },
    {
      id: "work-experience",
      title: "Qualifying Work Experience",
      description: "List current position first. A minimum of 2,000 hours of work experience specific to Prevention is required.",
      pdfPage: 10,
      fields: [
        { id: "work-experience-total-hours", label: "Total # of hours", type: "text", required: true, span: "third" },
        ...employmentBlockFields("employer-1", "Position 1 (current position)"),
        ...employmentBlockFields("employer-2", "Position 2"),
      ],
    },
    {
      id: "work-experience-continued",
      title: "Qualifying Work Experience (continued)",
      description: "Additional positions, if needed.",
      pdfPage: 11,
      fields: [
        ...employmentBlockFields("employer-3", "Position 3"),
        ...employmentBlockFields("employer-4", "Position 4"),
      ],
    },
    {
      id: "supervised-experience",
      title: "Supervised Prevention Experience",
      description: "This form is to be completed by the applicant's immediate supervisor, indicating the applicant's on-the-job supervision in the performance of the Prevention Performance Domains. Use Invite signer to send this section to your supervisor.",
      pdfPage: 12,
      signerSection: { role: "Immediate Supervisor" },
      notes: [
        "A more complete outline of the specific tasks for each domain is contained in the Certified Prevention Specialist Manual issued to the applicant.",
        "I. Program Coordination: monitoring evaluations; identify financial resources; identify ATOD resources; create materials; facilitate community awareness; facilitate building target population; document activities.",
        "II. Education and Training: conduct training assessments; address education needs; provide relevant information; select prevention materials; conduct training evaluations; provide prevention information; deliver culturally appropriate training.",
        "III. Community Organization: identify community stakeholders; identify specific issues; consult with community; establish network; construct prevention plan; increase community involvement; facilitate local leadership.",
        "IV. Public Policy: informing policy makers; establish working relationship; plan policy initiatives; influence fund allocations; inform policy makers of program effectiveness.",
        "V. Professional Growth and Responsibility: research prevention trends; model collaborative behavior; practice ethical behavior; recognize community norms; practice personal wellness.",
        "VI. Planning and Evaluation: review current literature; assess community needs; plan and evaluate projects; coordinate prevention plan with consumers to attain desired outcome.",
      ],
      fields: [
        { id: "supervised-applicant-name", label: "Applicant's name", type: "text", span: "full" },
        { id: "supervised-hours-domain-1", label: "I. Program Coordination — number of hours", type: "text", span: "half" },
        { id: "supervised-hours-domain-2", label: "II. Education and Training — number of hours", type: "text", span: "half" },
        { id: "supervised-hours-domain-3", label: "III. Community Organization — number of hours", type: "text", span: "half" },
        { id: "supervised-hours-domain-4", label: "IV. Public Policy — number of hours", type: "text", span: "half" },
        { id: "supervised-hours-domain-5", label: "V. Professional Growth and Responsibility — number of hours", type: "text", span: "half" },
        { id: "supervised-hours-domain-6", label: "VI. Planning and Evaluation — number of hours", type: "text", span: "half" },
        { id: "supervised-comments", label: "Additional comments", type: "textarea", span: "full" },
        { id: "supervised-supervisor-signature", label: "Supervisor's signature", type: "signature", span: "half", hint: "I hereby attest that supervised practical experience in performing prevention functions has been attained by the named applicant as outlined, with a minimum of 10 hours in each domain and 120 minimum total required hours." },
        { id: "supervised-supervisor-name-title", label: "Printed name and title", type: "text", span: "half" },
      ],
    },
    {
      id: "educational-record-formal",
      title: "Educational Record — Formal Education",
      description: "List all formal education and all education/training received specific to prevention of alcohol, tobacco, and other drug abuse.",
      pdfPage: 13,
      fields: [
        ...formalEducationFields("education-high-school", "High School"),
        ...formalEducationFields("education-university", "University"),
        ...formalEducationFields("education-post-graduate", "Post Graduate"),
      ],
    },
    {
      id: "educational-record-training",
      title: "Educational Record — Training",
      description: "List each prevention-specific course or training program. For Content areas, enter one or more of: Planning and Evaluation; Prevention Ed./Service Delivery; Communication; Community Organization; Public Policy/Environmental Change; Professional Growth/Responsibility.",
      pdfPage: 13,
      notes: [
        "A minimum of 120 education hours specific to the six performance domains is required, including 24 hours specific to ATOD, six hours of prevention ethics, and four hours of HIV/AIDS education.",
        "Additional training beyond these rows may be listed on a separate sheet uploaded in the Documents section of your portal.",
        "Attach documentation which supports all training (certificates, transcripts, etc.) in the Documents section of your portal. Lack of appropriate documentation shall result in nullification of all unsubstantiated hours.",
      ],
      table: {
        id: "training-log",
        columns: [
          { id: "title", label: "Course / Program title", width: "wide" },
          { id: "dates", label: "Dates attended", width: "narrow" },
          { id: "hours", label: "Clock / Credit hrs.", width: "narrow" },
          { id: "sponsor", label: "Sponsoring organization", width: "wide" },
          { id: "content", label: "Content (one or more areas)", width: "wide" },
        ],
        rows: 9,
      },
    },
    {
      id: "code-of-ethics",
      title: "Code of Ethics",
      description: "Summary of the ABCAC Code of Ethics for Prevention Specialists (full text on pages 16-17 of the application manual).",
      pdfPage: 16,
      notes: [
        "Non-Discrimination: the ATOD prevention specialist must not discriminate against clients, the public or others based on race, religion, age, sex, national ancestry, sexual orientation or economic condition, or against persons with disabilities.",
        "Responsibilities: exercise competent professional judgement when dealing with clients, the public and other professionals, and maintain their best interests at all times.",
        "Competence: provide competent professional service in keeping with ABCAC standards; assess personal competence and do not operate beyond your skill or training level; maintain current knowledge through ongoing professional education.",
        "Professional Standards: do not claim qualifications you do not possess, participate in relationships that mislead the public, misrepresent your certification, compromise your professional status through commercial endorsements, or fail to recognize professional impairment and the need to seek treatment.",
        "Professional Obligations to the Public: do not champion your own cause by denigrating others or engage in false or misleading communications about your own or other professionals' abilities, training and/or expertise.",
        "Publications: acknowledge and document any materials, techniques or people used in creating opinions, papers, or books; do not use copyrighted materials without author approval.",
        "Public Welfare: maintain objectivity, integrity and the highest professional standards in delivering prevention services, holding the best interest of the public first.",
        "Confidentiality: adhere to all applicable state and federal laws and rules, including reporting child abuse/neglect or misconduct, data privacy and professional relationships.",
        "Professional Relationships: maintain an objective, non-possessive relationship with those served; never exploit them sexually, financially or emotionally; maintain the ability and willingness to make appropriate referrals.",
        "Professional Integrity: never knowingly make a false statement to ABCAC or any disciplinary authority; promptly alert colleagues of potentially unethical behavior; report violations of professional conduct to the appropriate authority.",
        "Financial Arrangements: do not personally accept gifts or gratuities for professional work above and beyond the fees being paid to the employing agency.",
        "Professional Promotion: strive to maintain and promote the integrity of certification and the advancement of the profession.",
      ],
    },
    {
      id: "code-of-ethics-acknowledgment",
      title: "Code of Ethics Acknowledgment",
      description: "I have read and understand the Code of Ethics for Prevention Specialists as certified by the Arizona Board for Certification of Addiction Counselors. I will, to the best of my ability, adhere to and honor this Code in professional and personal dealings.",
      pdfPage: 17,
      fields: [
        { id: "ethics-printed-name", label: "Applicant's printed name", type: "text", required: true, span: "full" },
        { id: "ethics-signature", label: "Applicant's signature", type: "signature", required: true, span: "half" },
        { id: "ethics-date", label: "Date", type: "date", required: true, span: "half" },
      ],
    },
    {
      id: "statement-of-understanding",
      title: "Statement of Understanding",
      pdfPage: 18,
      notes: [
        "The Certified Prevention Specialist is a certification level granted by ABCAC recognizing those persons working in the ATOD field who specialize in the education and prevention of such abuse. This level of certification does not certify nor authorize professional counseling, and does not imply any educational or experiential background for providing any form of ATOD counseling or therapy.",
        "I hereby request that ABCAC grant the Certified Prevention Specialist certificate to me based on the following assurances: I have read and understand the Code of Ethics for prevention specialists and commit myself to honor this Code in all my professional and personal transactions; any violation of this Code of Ethics may result in revocation of this certification and trust to practice.",
        "I hereby affirm that this application is made on my behalf and is entirely voluntary on my part. I authorize ABCAC to request and receive all records and/or information relating to my application, including verbal or written contacts with my employer(s), academic and training institutions, and/or other persons or organizations having pertinent information. This constitutes my waiver of privilege that may otherwise exist in respect to the disclosure of such information.",
        "I certify that the information given herein is true and complete to the best of my knowledge and belief. I understand that intentionally false or misleading statements on this application will result in my being declared ineligible for certification. Data from this application may be used for statistical purposes.",
      ],
      fields: [
        { id: "understanding-printed-name", label: "Applicant's printed name", type: "text", required: true, span: "full" },
        { id: "understanding-signature", label: "Applicant's signature", type: "signature", required: true, span: "half" },
        { id: "understanding-date", label: "Date", type: "date", required: true, span: "half" },
      ],
    },
    {
      id: "supervisor-evaluation",
      title: "Supervisor Evaluation",
      description: "Present this form to your immediate supervisor familiar with the professional quality of your work; the completed evaluation must be returned to ABCAC directly by the supervisor. Use Invite signer to send this section securely.",
      pdfPage: 19,
      signerSection: { role: "Supervisor Evaluator" },
      notes: [
        "To the evaluator: the applicant is applying to be certified as a prevention specialist in the State of Arizona and will be placed in a position of trust. Your evaluation and those received from other sources will assist in determining the applicant's eligibility and qualification for certification.",
        "While all information obtained is confidential, the applicant may have access to this form. If you cannot truthfully complete this evaluation, please return it to the applicant. Please submit the completed form within 10 days directly to ABCAC.",
      ],
      fields: [
        { id: "sup-eval-applicant", label: "Applicant", type: "text", span: "full" },
        { id: "sup-eval-agency-street", label: "Agency address (number & street)", type: "text", span: "full" },
        { id: "sup-eval-agency-city-state-zip", label: "City / State / ZIP code", type: "text", span: "half" },
        { id: "sup-eval-agency-phone", label: "Agency phone", type: "text", span: "half" },
        { id: "sup-eval-agency-fax", label: "Fax #", type: "text", span: "half" },
        { id: "sup-eval-supervisor", label: "Immediate supervisor (title, last, first, MI)", type: "text", span: "half" },
        { id: "sup-eval-evaluator-name", label: "Name of person evaluating", type: "text", span: "full" },
        { id: "sup-eval-evaluator-street", label: "Address (number & street)", type: "text", span: "full" },
        { id: "sup-eval-evaluator-city-state-zip", label: "City / State / ZIP code", type: "text", span: "half" },
        { id: "sup-eval-evaluator-phone", label: "Phone", type: "text", span: "half" },
        { id: "sup-eval-evaluator-title", label: "Title / Position", type: "text", span: "half" },
        { id: "sup-eval-known-how-long", label: "How long have you known the applicant?", type: "text", span: "half" },
        { id: "sup-eval-direct-observation", label: "Is this evaluation based on direct observation of the applicant's work?", type: "yesno" },
        { id: "sup-eval-observation-frequency", label: "If yes: frequency of observation (Daily / Weekly / Other — explain)", type: "text", span: "half" },
        { id: "sup-eval-no-observation-explain", label: "If no, please explain", type: "text", span: "half" },
        { id: "sup-eval-comments", label: "Comments", type: "textarea", span: "full" },
      ],
    },
    {
      id: "supervisor-evaluation-ratings",
      title: "Supervisor Evaluation — Attribute or Skill Evaluation",
      description: "On the basis of your knowledge of this person, rate the applicant's skill in each area.",
      pdfPage: 20,
      signerSection: { role: "Supervisor Evaluator" },
      notes: RATING_SCALE_NOTES,
      table: {
        id: "sup-eval-ratings",
        columns: [
          { id: "attribute", label: "Attribute or skill", width: "wide" },
          { id: "score", label: "Score", width: "narrow" },
        ],
        rows: 15,
        fixedFirstColumn: RATING_ATTRIBUTES,
      },
      fields: [
        { id: "sup-eval-signature", label: "Signature", type: "signature", span: "half", hint: "I hereby certify that this rating is, to the best of my knowledge, truthful and it reflects as accurately as possible my knowledge of the applicant's skills in these areas." },
        { id: "sup-eval-signature-date", label: "Date", type: "date", span: "half" },
      ],
    },
    {
      id: "peer-reference-1",
      title: "Professional Reference (1)",
      description: "Present this form to two associates who are familiar with the professional quality of your work; the completed evaluation reference must be returned to ABCAC directly by the persons completing the form. Use Invite signer to send this section securely.",
      pdfPage: 21,
      signerSection: { role: "Professional Reference 1" },
      notes: [
        "To the evaluator: the applicant is applying to be certified as a prevention specialist in the State of Arizona and will be placed in a position of trust. Your evaluation and those received from other sources will assist in determining the applicant's eligibility and qualification for certification.",
        "While all information obtained is confidential, the applicant may have access to this form. If you cannot truthfully complete this evaluation, please return it to the applicant. Please submit the completed reference within 10 days directly to ABCAC.",
      ],
      fields: [
        { id: "ref1-applicant", label: "Applicant", type: "text", span: "full" },
        { id: "ref1-agency-street", label: "Agency address (number & street)", type: "text", span: "full" },
        { id: "ref1-agency-city-state-zip", label: "City / State / ZIP code", type: "text", span: "half" },
        { id: "ref1-agency-phone", label: "Agency phone", type: "text", span: "half" },
        { id: "ref1-agency-fax", label: "Fax #", type: "text", span: "half" },
        { id: "ref1-supervisor", label: "Immediate supervisor (title, last, first, MI)", type: "text", span: "half" },
        { id: "ref1-evaluator-name", label: "Name of person evaluating", type: "text", span: "full" },
        { id: "ref1-evaluator-street", label: "Address (number & street)", type: "text", span: "full" },
        { id: "ref1-evaluator-city-state-zip", label: "City / State / ZIP code", type: "text", span: "half" },
        { id: "ref1-evaluator-phone", label: "Phone", type: "text", span: "half" },
        { id: "ref1-known-how-long", label: "How long have you known the applicant?", type: "text", span: "half" },
        { id: "ref1-rel-supervisor", label: "Relationship to the applicant: Supervisor", type: "check", span: "third" },
        { id: "ref1-rel-colleague", label: "Relationship to the applicant: Colleague", type: "check", span: "third" },
        { id: "ref1-rel-other", label: "Other (explain)", type: "text", span: "third" },
        { id: "ref1-direct-observation", label: "Is the evaluation based on direct observation of the applicant's work?", type: "yesno" },
        { id: "ref1-no-observation-explain", label: "If no, please explain", type: "text", span: "full" },
        { id: "ref1-comments", label: "Comments", type: "textarea", span: "full" },
      ],
    },
    {
      id: "peer-reference-1-ratings",
      title: "Professional Reference (1) — Attribute or Skill Evaluation",
      description: "On the basis of your knowledge of this person, rate the applicant's skill in each area.",
      pdfPage: 22,
      signerSection: { role: "Professional Reference 1" },
      notes: RATING_SCALE_NOTES,
      table: {
        id: "ref1-ratings",
        columns: [
          { id: "attribute", label: "Attribute or skill", width: "wide" },
          { id: "score", label: "Score", width: "narrow" },
        ],
        rows: 15,
        fixedFirstColumn: RATING_ATTRIBUTES,
      },
      fields: [
        { id: "ref1-signature", label: "Signature", type: "signature", span: "half", hint: "I hereby certify that this rating is, to the best of my knowledge, truthful and it reflects as accurately as possible my knowledge of the applicant's skills in these areas." },
        { id: "ref1-signature-date", label: "Date", type: "date", span: "half" },
      ],
    },
    {
      id: "peer-reference-2",
      title: "Professional Reference (2)",
      description: "Present this form to two associates who are familiar with the professional quality of your work; the completed evaluation reference must be returned to ABCAC directly by the persons completing the form. Use Invite signer to send this section securely.",
      pdfPage: 23,
      signerSection: { role: "Professional Reference 2" },
      notes: [
        "To the evaluator: the applicant is applying to be certified as a prevention specialist in the State of Arizona and will be placed in a position of trust. Your evaluation and those received from other sources will assist in determining the applicant's eligibility and qualification for certification.",
        "While all information obtained is confidential, the applicant may have access to this form. If you cannot truthfully complete this evaluation, please return it to the applicant. Please submit the completed reference within 10 days directly to ABCAC.",
      ],
      fields: [
        { id: "ref2-applicant", label: "Applicant", type: "text", span: "full" },
        { id: "ref2-agency-street", label: "Agency address (number & street)", type: "text", span: "full" },
        { id: "ref2-agency-city-state-zip", label: "City / State / ZIP code", type: "text", span: "half" },
        { id: "ref2-agency-phone", label: "Agency phone", type: "text", span: "half" },
        { id: "ref2-agency-fax", label: "Fax #", type: "text", span: "half" },
        { id: "ref2-supervisor", label: "Immediate supervisor (title, last, first, MI)", type: "text", span: "half" },
        { id: "ref2-evaluator-name", label: "Name of person evaluating", type: "text", span: "full" },
        { id: "ref2-evaluator-street", label: "Address (number & street)", type: "text", span: "full" },
        { id: "ref2-evaluator-city-state-zip", label: "City / State / ZIP code", type: "text", span: "half" },
        { id: "ref2-evaluator-phone", label: "Phone", type: "text", span: "half" },
        { id: "ref2-known-how-long", label: "How long have you known the applicant?", type: "text", span: "half" },
        { id: "ref2-rel-supervisor", label: "Relationship to the applicant: Supervisor", type: "check", span: "third" },
        { id: "ref2-rel-colleague", label: "Relationship to the applicant: Colleague", type: "check", span: "third" },
        { id: "ref2-rel-other", label: "Other (explain)", type: "text", span: "third" },
        { id: "ref2-direct-observation", label: "Is the evaluation based on direct observation of the applicant's work?", type: "yesno" },
        { id: "ref2-no-observation-explain", label: "If no, please explain", type: "text", span: "full" },
        { id: "ref2-comments", label: "Comments", type: "textarea", span: "full" },
      ],
    },
    {
      id: "peer-reference-2-ratings",
      title: "Professional Reference (2) — Attribute or Skill Evaluation",
      description: "On the basis of your knowledge of this person, rate the applicant's skill in each area.",
      pdfPage: 24,
      signerSection: { role: "Professional Reference 2" },
      notes: RATING_SCALE_NOTES,
      table: {
        id: "ref2-ratings",
        columns: [
          { id: "attribute", label: "Attribute or skill", width: "wide" },
          { id: "score", label: "Score", width: "narrow" },
        ],
        rows: 15,
        fixedFirstColumn: RATING_ATTRIBUTES,
      },
      fields: [
        { id: "ref2-signature", label: "Signature", type: "signature", span: "half", hint: "I hereby certify that this rating is, to the best of my knowledge, truthful and it reflects as accurately as possible my knowledge of the applicant's skills in these areas." },
        { id: "ref2-signature-date", label: "Date", type: "date", span: "half" },
      ],
    },
    {
      id: "complaint-process",
      title: "Complaint Process (for reference)",
      description: "No entries are required in this section.",
      pdfPage: 25,
      notes: [
        "The complaint process is designed for individuals who believe they have been unfairly treated by any action of ABCAC, including denying certification or revocation of certification. Its purpose is only to determine whether ABCAC has acted accurately, adequately, and fairly in matters dealing with certification and recertification.",
        "A complaint is made in writing to the ABCAC Ethics Committee within thirty (30) days of notification of the CPS Committee's action of denying certification, revocation of certification, or denial of recertification. The document should state the reason the complaint is being made, why this reason is perceived as inaccurate, and include any necessary supporting data. Complaints not received within thirty (30) days of notification will not be processed; in that case ABCAC's initial action shall stand and all rights to appeal are forfeited.",
        "When a complaint is received, the ABCAC Ethics Committee will evaluate the action and/or decision made by the ABCAC CPS Committee, review supporting documents, and review the rationale for the challenge. The petitioner will receive written notification of the decision of the Ethics Committee within thirty (30) days. All monetary costs incurred by the petitioner shall remain the sole responsibility of the petitioner.",
      ],
    },
  ],
};
